apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-cloud-controller-manager
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
