/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/openshift/hypershift/api/karpenter/v1"
	karpenterv1 "github.com/openshift/hypershift/client/applyconfiguration/karpenter/v1"
	typedkarpenterv1 "github.com/openshift/hypershift/client/clientset/clientset/typed/karpenter/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeOpenshiftEC2NodeClasses implements OpenshiftEC2NodeClassInterface
type fakeOpenshiftEC2NodeClasses struct {
	*gentype.FakeClientWithListAndApply[*v1.OpenshiftEC2NodeClass, *v1.OpenshiftEC2NodeClassList, *karpenterv1.OpenshiftEC2NodeClassApplyConfiguration]
	Fake *FakeKarpenterV1
}

func newFakeOpenshiftEC2NodeClasses(fake *FakeKarpenterV1, namespace string) typedkarpenterv1.OpenshiftEC2NodeClassInterface {
	return &fakeOpenshiftEC2NodeClasses{
		gentype.NewFakeClientWithListAndApply[*v1.OpenshiftEC2NodeClass, *v1.OpenshiftEC2NodeClassList, *karpenterv1.OpenshiftEC2NodeClassApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("openshiftec2nodeclasses"),
			v1.SchemeGroupVersion.WithKind("OpenshiftEC2NodeClass"),
			func() *v1.OpenshiftEC2NodeClass { return &v1.OpenshiftEC2NodeClass{} },
			func() *v1.OpenshiftEC2NodeClassList { return &v1.OpenshiftEC2NodeClassList{} },
			func(dst, src *v1.OpenshiftEC2NodeClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1.OpenshiftEC2NodeClassList) []*v1.OpenshiftEC2NodeClass {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.OpenshiftEC2NodeClassList, items []*v1.OpenshiftEC2NodeClass) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
