apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift-controller-manager
  name: openshift-controller-manager
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: openshift-controller-manager
  type: ClusterIP
