apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-controller-manager
spec:
  endpoints:
  - metricRelabelings:
    - action: keep
      regex: openshift_build_status_phase_total
      sourceLabels:
      - __name__
    scheme: https
    targetPort: https
    tlsConfig:
      ca:
        configMap:
          key: ca.crt
          name: root-ca
      cert:
        secret:
          key: tls.crt
          name: metrics-client
      keySecret:
        key: tls.key
        name: metrics-client
      serverName: openshift-controller-manager
  namespaceSelector:
    matchNames:
    - HCP_NAMESPACE
  selector:
    matchLabels:
      app: openshift-controller-manager
