/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConcurrencyConfigurationApplyConfiguration represents a declarative configuration of the ConcurrencyConfiguration type for use
// with apply.
type ConcurrencyConfigurationApplyConfiguration struct {
	SlidingWindow *v1.Duration `json:"slidingWindow,omitempty"`
	Limit         *int32       `json:"limit,omitempty"`
}

// ConcurrencyConfigurationApplyConfiguration constructs a declarative configuration of the ConcurrencyConfiguration type for use with
// apply.
func ConcurrencyConfiguration() *ConcurrencyConfigurationApplyConfiguration {
	return &ConcurrencyConfigurationApplyConfiguration{}
}

// WithSlidingWindow sets the SlidingWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SlidingWindow field is set to the value of the last call.
func (b *ConcurrencyConfigurationApplyConfiguration) WithSlidingWindow(value v1.Duration) *ConcurrencyConfigurationApplyConfiguration {
	b.SlidingWindow = &value
	return b
}

// WithLimit sets the Limit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limit field is set to the value of the last call.
func (b *ConcurrencyConfigurationApplyConfiguration) WithLimit(value int32) *ConcurrencyConfigurationApplyConfiguration {
	b.Limit = &value
	return b
}
