/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ControlPlaneManagedServiceIdentitiesApplyConfiguration represents an declarative configuration of the ControlPlaneManagedServiceIdentities type for use
// with apply.
type ControlPlaneManagedServiceIdentitiesApplyConfiguration struct {
	ImageRegistryMSIClientID *string `json:"imageRegistryMSIClientID,omitempty"`
	IngressMSIClientID       *string `json:"ingressMSIClientID,omitempty"`
	NetworkMSIClientID       *string `json:"networkMSIClientID,omitempty"`
	StorageMSIClientID       *string `json:"storageMSIClientID,omitempty"`
}

// ControlPlaneManagedServiceIdentitiesApplyConfiguration constructs an declarative configuration of the ControlPlaneManagedServiceIdentities type for use with
// apply.
func ControlPlaneManagedServiceIdentities() *ControlPlaneManagedServiceIdentitiesApplyConfiguration {
	return &ControlPlaneManagedServiceIdentitiesApplyConfiguration{}
}

// WithImageRegistryMSIClientID sets the ImageRegistryMSIClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageRegistryMSIClientID field is set to the value of the last call.
func (b *ControlPlaneManagedServiceIdentitiesApplyConfiguration) WithImageRegistryMSIClientID(value string) *ControlPlaneManagedServiceIdentitiesApplyConfiguration {
	b.ImageRegistryMSIClientID = &value
	return b
}

// WithIngressMSIClientID sets the IngressMSIClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressMSIClientID field is set to the value of the last call.
func (b *ControlPlaneManagedServiceIdentitiesApplyConfiguration) WithIngressMSIClientID(value string) *ControlPlaneManagedServiceIdentitiesApplyConfiguration {
	b.IngressMSIClientID = &value
	return b
}

// WithNetworkMSIClientID sets the NetworkMSIClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkMSIClientID field is set to the value of the last call.
func (b *ControlPlaneManagedServiceIdentitiesApplyConfiguration) WithNetworkMSIClientID(value string) *ControlPlaneManagedServiceIdentitiesApplyConfiguration {
	b.NetworkMSIClientID = &value
	return b
}

// WithStorageMSIClientID sets the StorageMSIClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageMSIClientID field is set to the value of the last call.
func (b *ControlPlaneManagedServiceIdentitiesApplyConfiguration) WithStorageMSIClientID(value string) *ControlPlaneManagedServiceIdentitiesApplyConfiguration {
	b.StorageMSIClientID = &value
	return b
}
