apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      expireAfter: Never
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
disruption:
  consolidationPolicy: WhenEmptyOrUnderutilized
  consolidateAfter: Never
  budgets:
    - nodes: 100%
limits:
  cpu: 1000
  memory: 1000Gi
