/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	json "encoding/json"

	v1alpha1 "github.com/openshift/hypershift/api/scheduling/v1alpha1"
	schedulingv1alpha1 "github.com/openshift/hypershift/client/applyconfiguration/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterSizingConfigurations implements ClusterSizingConfigurationInterface
type FakeClusterSizingConfigurations struct {
	Fake *FakeSchedulingV1alpha1
}

var clustersizingconfigurationsResource = v1alpha1.SchemeGroupVersion.WithResource("clustersizingconfigurations")

var clustersizingconfigurationsKind = v1alpha1.SchemeGroupVersion.WithKind("ClusterSizingConfiguration")

// Get takes name of the clusterSizingConfiguration, and returns the corresponding clusterSizingConfiguration object, and an error if there is any.
func (c *FakeClusterSizingConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterSizingConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustersizingconfigurationsResource, name), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}

// List takes label and field selectors, and returns the list of ClusterSizingConfigurations that match those selectors.
func (c *FakeClusterSizingConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterSizingConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustersizingconfigurationsResource, clustersizingconfigurationsKind, opts), &v1alpha1.ClusterSizingConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterSizingConfigurationList{ListMeta: obj.(*v1alpha1.ClusterSizingConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterSizingConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterSizingConfigurations.
func (c *FakeClusterSizingConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustersizingconfigurationsResource, opts))
}

// Create takes the representation of a clusterSizingConfiguration and creates it.  Returns the server's representation of the clusterSizingConfiguration, and an error, if there is any.
func (c *FakeClusterSizingConfigurations) Create(ctx context.Context, clusterSizingConfiguration *v1alpha1.ClusterSizingConfiguration, opts v1.CreateOptions) (result *v1alpha1.ClusterSizingConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustersizingconfigurationsResource, clusterSizingConfiguration), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}

// Update takes the representation of a clusterSizingConfiguration and updates it. Returns the server's representation of the clusterSizingConfiguration, and an error, if there is any.
func (c *FakeClusterSizingConfigurations) Update(ctx context.Context, clusterSizingConfiguration *v1alpha1.ClusterSizingConfiguration, opts v1.UpdateOptions) (result *v1alpha1.ClusterSizingConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustersizingconfigurationsResource, clusterSizingConfiguration), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterSizingConfigurations) UpdateStatus(ctx context.Context, clusterSizingConfiguration *v1alpha1.ClusterSizingConfiguration, opts v1.UpdateOptions) (*v1alpha1.ClusterSizingConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustersizingconfigurationsResource, "status", clusterSizingConfiguration), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}

// Delete takes name of the clusterSizingConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeClusterSizingConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clustersizingconfigurationsResource, name, opts), &v1alpha1.ClusterSizingConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterSizingConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustersizingconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterSizingConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched clusterSizingConfiguration.
func (c *FakeClusterSizingConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSizingConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustersizingconfigurationsResource, name, pt, data, subresources...), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied clusterSizingConfiguration.
func (c *FakeClusterSizingConfigurations) Apply(ctx context.Context, clusterSizingConfiguration *schedulingv1alpha1.ClusterSizingConfigurationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ClusterSizingConfiguration, err error) {
	if clusterSizingConfiguration == nil {
		return nil, fmt.Errorf("clusterSizingConfiguration provided to Apply must not be nil")
	}
	data, err := json.Marshal(clusterSizingConfiguration)
	if err != nil {
		return nil, err
	}
	name := clusterSizingConfiguration.Name
	if name == nil {
		return nil, fmt.Errorf("clusterSizingConfiguration.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustersizingconfigurationsResource, *name, types.ApplyPatchType, data), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeClusterSizingConfigurations) ApplyStatus(ctx context.Context, clusterSizingConfiguration *schedulingv1alpha1.ClusterSizingConfigurationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ClusterSizingConfiguration, err error) {
	if clusterSizingConfiguration == nil {
		return nil, fmt.Errorf("clusterSizingConfiguration provided to Apply must not be nil")
	}
	data, err := json.Marshal(clusterSizingConfiguration)
	if err != nil {
		return nil, err
	}
	name := clusterSizingConfiguration.Name
	if name == nil {
		return nil, fmt.Errorf("clusterSizingConfiguration.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustersizingconfigurationsResource, *name, types.ApplyPatchType, data, "status"), &v1alpha1.ClusterSizingConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSizingConfiguration), err
}
