package omoperator

import (
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources"

	"k8s.io/client-go/dynamic"
)

func getOauthConfigSystemSessionSecret(ctx context.Context, mgmtKubeClient *dynamic.DynamicClient, controlPlaneNamespace string) (*libraryinputresources.Resource, error) {
	standaloneResourceNamespace := "openshift-authentication"
	standaloneResourceName := "v4-0-config-system-session"
	return getResourceToInputResources(ctx, coreSecretGVR, mgmtKubeClient, controlPlaneNamespace, hcpNameForNamespacedStandaloneResource(standaloneResourceNamespace, standaloneResourceName), standaloneResourceNamespace, standaloneResourceName)
}

func getOauthConfigSystemCliconfigConfigMap(ctx context.Context, mgmtKubeClient *dynamic.DynamicClient, controlPlaneNamespace string) (*libraryinputresources.Resource, error) {
	standaloneResourceNamespace := "openshift-authentication"
	standaloneResourceName := "v4-0-config-system-cliconfig"
	return getResourceToInputResources(ctx, coreConfigMapGVR, mgmtKubeClient, controlPlaneNamespace, hcpNameForNamespacedStandaloneResource(standaloneResourceNamespace, standaloneResourceName), standaloneResourceNamespace, standaloneResourceName)
}

func getOauthConfigSystemServingCert(ctx context.Context, mgmtKubeClient *dynamic.DynamicClient, controlPlaneNamespace string) (*libraryinputresources.Resource, error) {
	// in standalone, the oauth-server serving cert
	// comes from "openshift-authentication/v4-0-config-system-serving-cert" secret
	// which is generated by the service-ca operator
	//
	// in hcp the serving cert seems to be stored
	// under "controlPlaneNamespace/oauth-server-crt" secret
	//
	// for the POC we assume the above secret exists
	// and holds a valid serving cert

	standaloneResourceNamespace := "openshift-authentication"
	standaloneResourceName := "v4-0-config-system-serving-cert"
	return getResourceToInputResources(ctx, coreSecretGVR, mgmtKubeClient, controlPlaneNamespace, "oauth-server-crt", standaloneResourceNamespace, standaloneResourceName)
}

func getOauthConfigSystemServiceCA(ctx context.Context, mgmtKubeClient *dynamic.DynamicClient, controlPlaneNamespace string) (*libraryinputresources.Resource, error) {
	// in standalone, the masterCA field is filled
	// from "openshift-authentication/v4-0-config-system-service-ca" configmap
	// xref: https://github.com/openshift/cluster-authentication-operator/blob/817783a52d042f4ac3aa8faac7421ac013b42481/pkg/controllers/payload/payload_config_controller.go#L227
	//
	// in hcp the masterCA is filled from
	// "controlPlaneNamespace/oauth-master-ca-bundle" configmap
	//
	// for the POC we assume the above configmap exists
	// and holds a valid CA

	standaloneResourceNamespace := "openshift-authentication"
	standaloneResourceName := "v4-0-config-system-service-ca"
	return getResourceToInputResources(ctx, coreConfigMapGVR, mgmtKubeClient, controlPlaneNamespace, "oauth-master-ca-bundle", standaloneResourceNamespace, standaloneResourceName)
}

func getResourceToInputResources(ctx context.Context, gvr schema.GroupVersionResource, mgmtKubeClient *dynamic.DynamicClient, controlPlaneNamespace, controlPlaneResourceName, standaloneResourceNamespace, standaloneResourceName string) (*libraryinputresources.Resource, error) {
	unstructuredSecret, err := mgmtKubeClient.Resource(gvr).Namespace(controlPlaneNamespace).Get(ctx, controlPlaneResourceName, metav1.GetOptions{})
	if err != nil {
		return nil, err
	}

	unstructuredSecret.SetNamespace(standaloneResourceNamespace)
	unstructuredSecret.SetName(standaloneResourceName)
	return &libraryinputresources.Resource{
		ResourceType: gvr,
		Content:      unstructuredSecret,
	}, nil
}
