apiVersion: apps/v1
kind: Deployment
metadata:
  name: certified-operators-catalog
spec:
  selector:
    matchLabels:
      olm.catalogSource: certified-operators
  replicas: 1
  template:
    metadata:
      labels:
        olm.catalogSource: certified-operators
        app: certified-operators-catalog
        hypershift.openshift.io/control-plane-component: certified-operators-catalog
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: registry
          image: registry.redhat.io/redhat/certified-operator-index:v4.10
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
