apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redhat-marketplace-catalog-rollout
spec:
  concurrencyPolicy: Forbid
  schedule: CRON_SCHEDULE
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: catalog-rollout
          restartPolicy: Never
          containers:
          - name: rollout
            image: CLI_IMAGE
            imagePullPolicy: IfNotPresent
            command:
            - oc
            - rollout
            - restart
            - deployment/redhat-marketplace-catalog
