apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karpenter-operator
  namespace: HC_NAMESPACE
rules:
  - apiGroups:
      - "hypershift.openshift.io"
    resources:
      - "hostedclusters"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "get"
      - "list"
      - "watch"
