FROM registry.access.redhat.com/ubi10/ubi:10.0-1747220028

RUN dnf install -y haproxy-3.0.5-4.el10 socat-1.7.4.4-8.el10 \
  && dnf clean all

ENTRYPOINT [ "/usr/sbin/haproxy" ]
CMD ["-W", "-f", "/config/haproxy.cfg"]

LABEL name="multicluster-engine/hypershift-shared-ingress"
LABEL description="HyperShift's HAProxy 3 based Shared Ingress container"
LABEL summary="HyperShift Shared Ingress"
LABEL url="https://quay.io/repository/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-shared-ingress"
LABEL version="3.0.5-4"
LABEL com.redhat.component="multicluster-engine-hypershift-shared-ingress"
LABEL io.openshift.tags="data,images"
LABEL io.k8s.display-name="multicluster-engine-hypershift-shared-ingress"
