package hostedcluster

import (
	"context"
	"errors"
	"fmt"

	hyperv1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	"github.com/openshift/hypershift/support/oidc"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	"github.com/go-logr/logr"
)

const (
	gcpOIDCDocumentsFinalizer = "hypershift.io/gcp-oidc-discovery"
)

func (r *HostedClusterReconciler) reconcileGCPOIDCDocuments(ctx context.Context, log logr.Logger, hcluster *hyperv1.HostedCluster, hcp *hyperv1.HostedControlPlane) error {
	// Documents were already uploaded in a previous reconciliation; nothing to do.
	if controllerutil.ContainsFinalizer(hcluster, gcpOIDCDocumentsFinalizer) {
		return nil
	}

	// The user supplied their own signing key, meaning they are managing the
	// OIDC discovery documents externally (e.g. pre-configured WIF).
	if hcluster.Spec.ServiceAccountSigningKey != nil && hcluster.Spec.ServiceAccountSigningKey.Name != "" {
		return nil
	}

	// Neither an external signing key nor an operator-managed GCS bucket is
	// configured. WIF is a hard requirement for GCP, so this is an error.
	if r.GCPOIDCStorageBucketName == "" || r.GCSClient == nil {
		return fmt.Errorf("GCP OIDC document management requires either a ServiceAccountSigningKey (for pre-configured OIDC) or a GCS bucket (--gcp-oidc-storage-bucket-name) for operator-managed OIDC")
	}

	// Fetch the control-plane signing key generated by the CPO.
	// If it doesn't exist yet the CPO hasn't created it; return nil to retry.
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: hcp.Namespace,
			Name:      serviceAccountSigningKeySecret,
		},
	}
	if err := r.Client.Get(ctx, client.ObjectKeyFromObject(secret), secret); err != nil {
		if apierrors.IsNotFound(err) {
			log.Info("sa-signing-key secret not yet available, will retry", "secret", client.ObjectKeyFromObject(secret))
			return nil
		}
		return fmt.Errorf("failed to get controlplane service account signing key %q: %w", client.ObjectKeyFromObject(secret), err)
	}

	if _, ok := secret.Data[serviceSignerPublicKey]; !ok {
		return fmt.Errorf("controlplane service account signing key secret %q missing required key %s", client.ObjectKeyFromObject(secret), serviceSignerPublicKey)
	}

	params := oidc.OIDCGeneratorParams{
		IssuerURL: hcp.Spec.IssuerURL,
		PubKey:    secret.Data[serviceSignerPublicKey],
	}

	for path, generator := range oidcDocumentGenerators() {
		bodyReader, err := generator(params)
		if err != nil {
			return fmt.Errorf("failed to generate OIDC document %s: %w", path, err)
		}
		objectName := hcluster.Spec.InfraID + path
		if err := r.GCSClient.UploadObject(ctx, r.GCPOIDCStorageBucketName, objectName, bodyReader); err != nil {
			return fmt.Errorf("failed to upload %s to gs://%s/%s: %w", path, r.GCPOIDCStorageBucketName, objectName, err)
		}
		log.Info("Uploaded OIDC document to GCS", "path", path, "bucket", r.GCPOIDCStorageBucketName, "object", objectName)
	}

	if !controllerutil.ContainsFinalizer(hcluster, gcpOIDCDocumentsFinalizer) {
		controllerutil.AddFinalizer(hcluster, gcpOIDCDocumentsFinalizer)
		if err := r.Client.Update(ctx, hcluster); err != nil {
			return fmt.Errorf("failed to update the hosted cluster after adding the %s finalizer: %w", gcpOIDCDocumentsFinalizer, err)
		}
	}

	log.Info("Successfully uploaded GCP OIDC documents to GCS bucket", "bucket", r.GCPOIDCStorageBucketName)
	return nil
}

func (r *HostedClusterReconciler) cleanupGCPOIDCBucketData(ctx context.Context, log logr.Logger, hcluster *hyperv1.HostedCluster) error {
	// No finalizer means the operator never uploaded documents; nothing to clean up.
	if !controllerutil.ContainsFinalizer(hcluster, gcpOIDCDocumentsFinalizer) {
		return nil
	}

	// The finalizer is present, so we must have a GCS bucket to delete from.
	// If the operator lost its bucket config, we cannot proceed safely.
	if r.GCPOIDCStorageBucketName == "" || r.GCSClient == nil {
		return fmt.Errorf("hypershift operator was not configured with a GCS bucket; cannot clean up OIDC documents. Please set up the bucket or clean up manually and remove the %s finalizer", gcpOIDCDocumentsFinalizer)
	}

	var deleteErrors []error
	for path := range oidcDocumentGenerators() {
		objectName := hcluster.Spec.InfraID + path
		if err := r.GCSClient.DeleteObject(ctx, r.GCPOIDCStorageBucketName, objectName); err != nil {
			log.Error(err, "Failed to delete OIDC document from GCS", "object", objectName)
			deleteErrors = append(deleteErrors, err)
		}
	}

	if err := errors.Join(deleteErrors...); err != nil {
		return fmt.Errorf("failed to delete OIDC documents from GCS bucket %s: %w", r.GCPOIDCStorageBucketName, err)
	}

	controllerutil.RemoveFinalizer(hcluster, gcpOIDCDocumentsFinalizer)
	if err := r.Client.Update(ctx, hcluster); err != nil {
		return fmt.Errorf("failed to update hostedcluster after removing %s finalizer: %w", gcpOIDCDocumentsFinalizer, err)
	}

	log.Info("Cleaned up GCP OIDC documents from GCS bucket", "bucket", r.GCPOIDCStorageBucketName)
	return nil
}
