---
apiVersion: v1
kind: Namespace
metadata:
  name: hypershift-ops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: hypershift-ops
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "hypershift-ops:admin"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: hypershift-ops
    name: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: hypershift
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hypershift-operator
  namespace: hypershift
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/hypershift/hypershift-operator:latest
      referencePolicy:
        type: Local
      importPolicy:
        scheduled: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: hypershift
  name: installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hypershift-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    namespace: hypershift
    name: installer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hypershift-operator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"installer\")].image"}]'
  name: installer
  namespace: hypershift
spec:
  replicas: 1
  selector:
    matchLabels:
      name: installer
  template:
    metadata:
      labels:
        name: installer
    spec:
      initContainers:
        - args:
            - -c
            - |
              #!/bin/bash
              set -euo pipefail
              
              /usr/bin/oc get istag -n hypershift hypershift-operator:latest -ojsonpath='{.image.dockerImageReference}' > /installer-data/image-ref
          command:
            - /bin/bash
          image: quay.io/openshift/origin-cli:latest
          name: get-image
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - mountPath: /installer-data
              name: data
      containers:
        - args:
            - -c
            - |
              #!/bin/bash
              set -euo pipefail
              
              /usr/bin/hypershift install \
              --hypershift-image=\$(cat /installer-data/image-ref)
              
              /usr/bin/sleep infinity
          command:
            - /bin/bash
          image: quay.io/hypershift/hypershift-operator:latest
          name: installer
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - mountPath: /installer-data
              name: data
      serviceAccountName: installer
      terminationGracePeriodSeconds: 3
      volumes:
        - name: data
          emptyDir: {}
