apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "certified-operators"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/certified-operator-index:v4.8
  displayName: "Certified Operators"
  publisher: "Red Hat"
  priority: -200
  updateStrategy:
    registryPoll:
      interval: 10m
