apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-marketplace-catalog
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    image.openshift.io/triggers: |-
      [{"from":{"kind":"ImageStreamTag","name":"redhat-marketplace-catalogs:v4.8"},"fieldPath":"spec.template.spec.containers[?(@.name==\"registry\")].image"}]
spec:
  selector:
    matchLabels:
      olm.catalogSource: redhat-marketplace
  replicas: 1
  template:
    metadata:
      labels:
        olm.catalogSource: redhat-marketplace
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: registry
          image: registry.redhat.io/redhat/redhat-marketplace-index:v4.8
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-addr=:50051'
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 340Mi
