apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-operator
  labels:
    app: olm-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: olm-operator
  template:
    metadata:
      annotations:
        workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: olm-operator
    spec:
      priorityClassName: "system-cluster-critical"
      containers:
        - name: olm-operator
          command:
            - /bin/olm
          args:
            - --namespace
            - $(OPERATOR_NAMESPACE)
            - --writeStatusName
            - operator-lifecycle-manager
            - --writePackageServerStatusName
            - "\"\""
            - --tls-cert
            - /var/run/secrets/serving-cert/tls.crt
            - --tls-key
            - /var/run/secrets/serving-cert/tls.key
          image: {{ imageFor "operator-lifecycle-manager" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
            - containerPort: 8081
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: RELEASE_VERSION
              value: {{ version "release" }}
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: olm-operator
            - name: KUBECONFIG
              value: /etc/openshift/kubeconfig/kubeconfig
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
          volumeMounts:
            - mountPath: /var/run/secrets/serving-cert
              name: serving-cert
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
      volumes:
        - name: serving-cert
          secret:
            secretName: olm-operator-serving-cert
        - name: kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
