version: "2"
run:
  timeout: 10m
  allow-parallel-runners: true
output:
  sort-results: true
severity:
  default-severity: error
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: "module"
        description: kubeapilinter is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              - "maxlength"
              - "nobools"
              - "nomaps"
              - "statussubresource"
            disable:
              - "optionalfields"
              - "requiredfields"
              - "ssatags"
              - "integers"
              - "commentstart"
              - "jsontags"
              - "conditions"
              - "optionalorrequired"
              - "uniquemarkers"


