version: "2"
run:
  timeout: 10m
  allow-parallel-runners: true
output:
  sort-results: true
severity:
  default-severity: error
issues:
  max-issues-per-linter: 0  # 0 = unlimited
  max-same-issues: 0        # 0 = unlimited
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - kubeapilinter
    - misspell
    - staticcheck
    - unused
  exclusions:
    rules:
      # Run kubeapilinter only on api directory by excluding it everywhere else
      - path-except: '^(api/|hypershift/api/)'
        linters:
          - kubeapilinter
      # Exclude SA1019 deprecation warnings for corev1.Endpoints
      - text: "SA1019.*corev1\\.Endpoints.*deprecated.*Use discoveryv1\\.EndpointSlice"
        linters:
          - staticcheck
      - text: "SA1019.*corev1\\.EndpointSubset.*deprecated"
        linters:
          - staticcheck
  settings:
    custom:
      kubeapilinter:
        type: "module"
        description: kubeapilinter is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              - "maxlength"
              - "nobools"
              - "nomaps"
              - "statussubresource"
          lintersConfig:
            conditions:
              isFirstField: Warn
              useProtobuf: Ignore
              usePatchStrategy: Ignore
    misspell:
      # The use of US spelling over other English spellings, like UK, is inline with the OpenShift conventions:
      # https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#terminology-grammar-and-spelling
      locale: US
      ignore-rules:
        - nto
    staticcheck:
      dot-import-whitelist:
        - "github.com/onsi/gomega"
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - dot
        - prefix(github.com/openshift/hypershift)
        - prefix(github.com/openshift)
        - prefix(github.com/aws)
        - prefix(github.com/Azure)
        - prefix(k8s.io)
        - prefix(sigs.k8s.io)
        - default
      custom-order: true
