version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - misspell
  settings:
    misspell:
      # The use of US spelling over other English spellings, like UK, is inline with the OpenShift conventions:
      # https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#terminology-grammar-and-spelling
      locale: US
      # Typos to ignore.
      # Should be in lower case.
      ignore-rules:
        - nto
  exclusions:
    warn-unused: true
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: hcp.Status.Version is deprecated: Use versionStatus.desired.version instead.'
      - linters:
          - staticcheck
        text: 'SA1019: hcp.Status.ReleaseImage is deprecated: Use versionStatus.desired.image instead.'
      - linters:
          - staticcheck
        text: 'SA1019: hcp.Status.LastReleaseImageTransitionTime is deprecated'
      - linters:
          - staticcheck
        text: 'SA1019: infra.Status.Platform is deprecated: Use platformStatus.type instead'
      - linters:
          - unused
        text: const tuningConfigKey is unused
      - linters:
          - staticcheck
        text: 'ST1001: should not use dot imports'
        source: 'github.com/onsi/gomega'
      - linters:
          - staticcheck
        text: 'ST1005: error strings should not be capitalized'
        source: 'Konnectivity'
      - linters:
          - staticcheck
        text: 'QF1008'
      - linters:
          - staticcheck
        text: 'QF1007'
      - linters:
          - staticcheck
        text: 'QF1001'
      # aws-sdk-go v1 is deprecated but migration to v2 is a separate effort
      - linters:
          - staticcheck
        text: 'SA1019: "github.com/aws/aws-sdk-go'
      # cluster-api v1beta1 is deprecated but migration to v1beta2 is a separate effort
      - linters:
          - staticcheck
        text: 'SA1019: "sigs.k8s.io/cluster-api/(.*)" is deprecated: This package is deprecated and is going to be removed when support for v1beta1 will be dropped.'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - dot
        - prefix(github.com/openshift/hypershift)
        - prefix(github.com/openshift)
        - prefix(github.com/aws)
        - prefix(github.com/Azure)
        - prefix(k8s.io)
        - prefix(sigs.k8s.io)
        - default
      custom-order: true
  exclusions:
    warn-unused: true
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
