builds:
- id: hypershift-operator
  main: ./hypershift-operator
  flags:
  - -mod=vendor
- id: control-plane-operator
  main: ./control-plane-operator
  flags:
  - -mod=vendor
- id: hypershift
  main: .
  flags:
  - -mod=vendor
defaultBaseImage: gcr.io/distroless/static:debug-nonroot
