FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.24-openshift-4.21 AS builder

WORKDIR /hypershift

COPY . .

RUN make test-extend

# Multi-stage build lets us drop the source code and build cache from the final image
FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.24-openshift-4.21

WORKDIR /hypershift

RUN mkdir -p /hypershift/bin
COPY --from=builder /hypershift/bin/hypershift-test-extend /hypershift/bin/hypershift-test-extend
