FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10 AS builder

WORKDIR /hypershift

COPY . .

RUN make control-plane-operator

FROM registry.ci.openshift.org/ocp/4.10:base
COPY --from=builder /hypershift/bin/control-plane-operator /usr/bin/control-plane-operator

ENTRYPOINT /usr/bin/control-plane-operator
