FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.18 AS builder

WORKDIR /hypershift

COPY . .

RUN yum -y install azure-cli && \
    yum clean all

RUN make e2e
