/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apihypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	clientset "github.com/openshift/hypershift/client/clientset/clientset"
	internalinterfaces "github.com/openshift/hypershift/client/informers/externalversions/internalinterfaces"
	hypershiftv1beta1 "github.com/openshift/hypershift/client/listers/hypershift/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GCPPrivateServiceConnectInformer provides access to a shared informer and lister for
// GCPPrivateServiceConnects.
type GCPPrivateServiceConnectInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() hypershiftv1beta1.GCPPrivateServiceConnectLister
}

type gCPPrivateServiceConnectInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGCPPrivateServiceConnectInformer constructs a new informer for GCPPrivateServiceConnect type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGCPPrivateServiceConnectInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGCPPrivateServiceConnectInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGCPPrivateServiceConnectInformer constructs a new informer for GCPPrivateServiceConnect type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGCPPrivateServiceConnectInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HypershiftV1beta1().GCPPrivateServiceConnects(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HypershiftV1beta1().GCPPrivateServiceConnects(namespace).Watch(context.TODO(), options)
			},
		},
		&apihypershiftv1beta1.GCPPrivateServiceConnect{},
		resyncPeriod,
		indexers,
	)
}

func (f *gCPPrivateServiceConnectInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGCPPrivateServiceConnectInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gCPPrivateServiceConnectInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apihypershiftv1beta1.GCPPrivateServiceConnect{}, f.defaultInformer)
}

func (f *gCPPrivateServiceConnectInformer) Lister() hypershiftv1beta1.GCPPrivateServiceConnectLister {
	return hypershiftv1beta1.NewGCPPrivateServiceConnectLister(f.Informer().GetIndexer())
}
