/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apihypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	clientset "github.com/openshift/hypershift/client/clientset/clientset"
	internalinterfaces "github.com/openshift/hypershift/client/informers/externalversions/internalinterfaces"
	hypershiftv1beta1 "github.com/openshift/hypershift/client/listers/hypershift/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IgnitionPayloadInformer provides access to a shared informer and lister for
// IgnitionPayloads.
type IgnitionPayloadInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() hypershiftv1beta1.IgnitionPayloadLister
}

type ignitionPayloadInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIgnitionPayloadInformer constructs a new informer for IgnitionPayload type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIgnitionPayloadInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIgnitionPayloadInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIgnitionPayloadInformer constructs a new informer for IgnitionPayload type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIgnitionPayloadInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HypershiftV1beta1().IgnitionPayloads(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HypershiftV1beta1().IgnitionPayloads(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HypershiftV1beta1().IgnitionPayloads(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HypershiftV1beta1().IgnitionPayloads(namespace).Watch(ctx, options)
			},
		},
		&apihypershiftv1beta1.IgnitionPayload{},
		resyncPeriod,
		indexers,
	)
}

func (f *ignitionPayloadInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIgnitionPayloadInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ignitionPayloadInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apihypershiftv1beta1.IgnitionPayload{}, f.defaultInformer)
}

func (f *ignitionPayloadInformer) Lister() hypershiftv1beta1.IgnitionPayloadLister {
	return hypershiftv1beta1.NewIgnitionPayloadLister(f.Informer().GetIndexer())
}
