apiVersion: v1
data:
  policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    metadata:
      creationTimestamp: null
      name: policy
    omitManagedFields: true
    omitStages:
    - RequestReceived
    rules:
    - level: None
      resources:
      - resources:
        - events
    - level: None
      nonResourceURLs:
      - /api*
      - /version
      - /healthz
      - /readyz
      userGroups:
      - system:authenticated
      - system:unauthenticated
    - level: None
      namespaces:
      - ""
      resources:
      - group: apiserver.openshift.io
        resources:
        - apirequestcounts
        - apirequestcounts/*
      users:
      - system:apiserver
    - level: RequestResponse
      resources:
      - group: user.openshift.io
        resources:
        - identities
      - group: oauth.openshift.io
        resources:
        - oauthaccesstokens
        - oauthauthorizetokens
      verbs:
      - create
      - update
      - patch
      - delete
    - level: Metadata
      omitStages:
      - RequestReceived
  profile: Default
kind: ConfigMap
metadata:
  name: kas-audit-config
  namespace: HCP_NAMESPACE
