apiVersion: v1
data:
  kubeconfig: ""
kind: Secret
metadata:
  labels:
    hypershift.openshift.io/kubeconfig: service
  name: service-network-admin-kubeconfig
  namespace: HCP_NAMESPACE
type: Opaque
