// Code generated by delegatingclientgenerator. DO NOT EDIT.

package awsapi

//go:generate ../../hack/tools/bin/mockgen -source=route53.go -package=awsapi -destination=route53_mock.go

import (
	"context"

	route53v2 "github.com/aws/aws-sdk-go-v2/service/route53"
)

// ROUTE53API defines the ROUTE53 operations used by HyperShift.
// Generated from: cmd/infra/aws/iam.go + delegatingclientgenerator extendedAPIs
//
// This interface includes methods from IAM delegation policies as well as additional
// methods used by CLI tools with full credentials. Only the delegated subset is
// implemented by the delegating client; non-delegated methods will panic if called
// through the delegating path (matching v1 behavior).
type ROUTE53API interface {
	AssociateVPCWithHostedZone(ctx context.Context, input *route53v2.AssociateVPCWithHostedZoneInput, optFns ...func(*route53v2.Options)) (*route53v2.AssociateVPCWithHostedZoneOutput, error)
	ChangeResourceRecordSets(ctx context.Context, input *route53v2.ChangeResourceRecordSetsInput, optFns ...func(*route53v2.Options)) (*route53v2.ChangeResourceRecordSetsOutput, error)
	CreateHostedZone(ctx context.Context, input *route53v2.CreateHostedZoneInput, optFns ...func(*route53v2.Options)) (*route53v2.CreateHostedZoneOutput, error)
	CreateVPCAssociationAuthorization(ctx context.Context, input *route53v2.CreateVPCAssociationAuthorizationInput, optFns ...func(*route53v2.Options)) (*route53v2.CreateVPCAssociationAuthorizationOutput, error)
	DeleteHostedZone(ctx context.Context, input *route53v2.DeleteHostedZoneInput, optFns ...func(*route53v2.Options)) (*route53v2.DeleteHostedZoneOutput, error)
	DisassociateVPCFromHostedZone(ctx context.Context, input *route53v2.DisassociateVPCFromHostedZoneInput, optFns ...func(*route53v2.Options)) (*route53v2.DisassociateVPCFromHostedZoneOutput, error)
	GetHostedZone(ctx context.Context, input *route53v2.GetHostedZoneInput, optFns ...func(*route53v2.Options)) (*route53v2.GetHostedZoneOutput, error)
	ListHostedZones(ctx context.Context, input *route53v2.ListHostedZonesInput, optFns ...func(*route53v2.Options)) (*route53v2.ListHostedZonesOutput, error)
	ListHostedZonesByVPC(ctx context.Context, input *route53v2.ListHostedZonesByVPCInput, optFns ...func(*route53v2.Options)) (*route53v2.ListHostedZonesByVPCOutput, error)
	ListResourceRecordSets(ctx context.Context, input *route53v2.ListResourceRecordSetsInput, optFns ...func(*route53v2.Options)) (*route53v2.ListResourceRecordSetsOutput, error)
}

// Ensure *route53v2.Client implements ROUTE53API
var _ ROUTE53API = (*route53v2.Client)(nil)
