apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hosted-cluster-config-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - pods
  verbs:
  - get
  - patch
  - update
  - create
  - list
  - watch
- apiGroups: ["extensions", "apps"]
  resources:
  - deployments
  verbs:
  - get
  - patch
  - update
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
  - delete
