/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GCPPrivateServiceConnectLister helps list GCPPrivateServiceConnects.
// All objects returned here must be treated as read-only.
type GCPPrivateServiceConnectLister interface {
	// List lists all GCPPrivateServiceConnects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hypershiftv1beta1.GCPPrivateServiceConnect, err error)
	// GCPPrivateServiceConnects returns an object that can list and get GCPPrivateServiceConnects.
	GCPPrivateServiceConnects(namespace string) GCPPrivateServiceConnectNamespaceLister
	GCPPrivateServiceConnectListerExpansion
}

// gCPPrivateServiceConnectLister implements the GCPPrivateServiceConnectLister interface.
type gCPPrivateServiceConnectLister struct {
	listers.ResourceIndexer[*hypershiftv1beta1.GCPPrivateServiceConnect]
}

// NewGCPPrivateServiceConnectLister returns a new GCPPrivateServiceConnectLister.
func NewGCPPrivateServiceConnectLister(indexer cache.Indexer) GCPPrivateServiceConnectLister {
	return &gCPPrivateServiceConnectLister{listers.New[*hypershiftv1beta1.GCPPrivateServiceConnect](indexer, hypershiftv1beta1.Resource("gcpprivateserviceconnect"))}
}

// GCPPrivateServiceConnects returns an object that can list and get GCPPrivateServiceConnects.
func (s *gCPPrivateServiceConnectLister) GCPPrivateServiceConnects(namespace string) GCPPrivateServiceConnectNamespaceLister {
	return gCPPrivateServiceConnectNamespaceLister{listers.NewNamespaced[*hypershiftv1beta1.GCPPrivateServiceConnect](s.ResourceIndexer, namespace)}
}

// GCPPrivateServiceConnectNamespaceLister helps list and get GCPPrivateServiceConnects.
// All objects returned here must be treated as read-only.
type GCPPrivateServiceConnectNamespaceLister interface {
	// List lists all GCPPrivateServiceConnects in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hypershiftv1beta1.GCPPrivateServiceConnect, err error)
	// Get retrieves the GCPPrivateServiceConnect from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hypershiftv1beta1.GCPPrivateServiceConnect, error)
	GCPPrivateServiceConnectNamespaceListerExpansion
}

// gCPPrivateServiceConnectNamespaceLister implements the GCPPrivateServiceConnectNamespaceLister
// interface.
type gCPPrivateServiceConnectNamespaceLister struct {
	listers.ResourceIndexer[*hypershiftv1beta1.GCPPrivateServiceConnect]
}
