/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HCPEtcdBackupLister helps list HCPEtcdBackups.
// All objects returned here must be treated as read-only.
type HCPEtcdBackupLister interface {
	// List lists all HCPEtcdBackups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hypershiftv1beta1.HCPEtcdBackup, err error)
	// HCPEtcdBackups returns an object that can list and get HCPEtcdBackups.
	HCPEtcdBackups(namespace string) HCPEtcdBackupNamespaceLister
	HCPEtcdBackupListerExpansion
}

// hCPEtcdBackupLister implements the HCPEtcdBackupLister interface.
type hCPEtcdBackupLister struct {
	listers.ResourceIndexer[*hypershiftv1beta1.HCPEtcdBackup]
}

// NewHCPEtcdBackupLister returns a new HCPEtcdBackupLister.
func NewHCPEtcdBackupLister(indexer cache.Indexer) HCPEtcdBackupLister {
	return &hCPEtcdBackupLister{listers.New[*hypershiftv1beta1.HCPEtcdBackup](indexer, hypershiftv1beta1.Resource("hcpetcdbackup"))}
}

// HCPEtcdBackups returns an object that can list and get HCPEtcdBackups.
func (s *hCPEtcdBackupLister) HCPEtcdBackups(namespace string) HCPEtcdBackupNamespaceLister {
	return hCPEtcdBackupNamespaceLister{listers.NewNamespaced[*hypershiftv1beta1.HCPEtcdBackup](s.ResourceIndexer, namespace)}
}

// HCPEtcdBackupNamespaceLister helps list and get HCPEtcdBackups.
// All objects returned here must be treated as read-only.
type HCPEtcdBackupNamespaceLister interface {
	// List lists all HCPEtcdBackups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hypershiftv1beta1.HCPEtcdBackup, err error)
	// Get retrieves the HCPEtcdBackup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hypershiftv1beta1.HCPEtcdBackup, error)
	HCPEtcdBackupNamespaceListerExpansion
}

// hCPEtcdBackupNamespaceLister implements the HCPEtcdBackupNamespaceLister
// interface.
type hCPEtcdBackupNamespaceLister struct {
	listers.ResourceIndexer[*hypershiftv1beta1.HCPEtcdBackup]
}
