apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-plane-pki-operator
rules:
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes
  verbs:
  - get
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - certificates.hypershift.openshift.io
  resources:
  - certificatesigningrequestapprovals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.hypershift.openshift.io
  resources:
  - certificaterevocationrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.hypershift.openshift.io
  resources:
  - certificaterevocationrequests/status
  verbs:
  - patch
