apiVersion: v1
kind: Service
metadata:
  name: external-oidc-webhook
spec:
  type: ClusterIP
  selector:
    app: external-oidc-webhook
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
