apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api.openshift.io/merged-by-featuregates: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: certificatesigningrequestapprovals.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: CertificateSigningRequestApproval
    listKind: CertificateSigningRequestApprovalList
    plural: certificatesigningrequestapprovals
    shortNames:
    - csra
    - csras
    singular: certificatesigningrequestapproval
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: CertificateSigningRequestApproval defines the desired state of
          CertificateSigningRequestApproval
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: CertificateSigningRequestApprovalSpec defines the desired
              state of CertificateSigningRequestApproval
            type: object
          status:
            description: CertificateSigningRequestApprovalStatus defines the observed
              state of CertificateSigningRequestApproval
            type: object
        type: object
    served: true
    storage: true
