apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: cluster-autoscaler
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scheme: http