apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-autoscaler
  namespace: HCP_NAMESPACE
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  - machinedeployments/scale
  - machines
  - machinesets
  - machinesets/scale
  - machinepools
  - machinepools/scale
  verbs:
  - '*'
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - capi-provider.agent-install.openshift.io
  resources:
  - agentmachinetemplates
  verbs:
  - get
  - list
