apiVersion: v1
kind: Service
metadata:
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/serving-cert-secret-name: cluster-baremetal-webhook-server-cert
  labels:
    k8s-app: cluster-baremetal-operator
  name: cluster-baremetal-webhook-service
  namespace: HCP_NAMESPACE
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    k8s-app: cluster-baremetal-operator
  sessionAffinity: None
  type: ClusterIP
