apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanroles
  namespace: hypershift
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanroles
            image: quay.io/hypershift/cleanroles:latest
            command: ["/cleanroles/cleanroles"]
            env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ROLE_ARN
              value: "arn:aws:iam::820196288204:role/hypershift-ci-2-cleanroles"
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: "/var/run/secrets/openshift/token"
            imagePullPolicy: Always
            volumeMounts:
            - name: token
              mountPath: /var/run/secrets/openshift
              readOnly: true
          restartPolicy: Never
          serviceAccountName: cleanroles
          volumes:
          - name: token
            projected:
              sources:
              - serviceAccountToken:
                  path: token
                  audience: openshift
