/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	certificatesv1alpha1 "github.com/openshift/hypershift/api/certificates/v1alpha1"
	applyconfigurationcertificatesv1alpha1 "github.com/openshift/hypershift/client/applyconfiguration/certificates/v1alpha1"
	scheme "github.com/openshift/hypershift/client/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CertificateSigningRequestApprovalsGetter has a method to return a CertificateSigningRequestApprovalInterface.
// A group's client should implement this interface.
type CertificateSigningRequestApprovalsGetter interface {
	CertificateSigningRequestApprovals(namespace string) CertificateSigningRequestApprovalInterface
}

// CertificateSigningRequestApprovalInterface has methods to work with CertificateSigningRequestApproval resources.
type CertificateSigningRequestApprovalInterface interface {
	Create(ctx context.Context, certificateSigningRequestApproval *certificatesv1alpha1.CertificateSigningRequestApproval, opts v1.CreateOptions) (*certificatesv1alpha1.CertificateSigningRequestApproval, error)
	Update(ctx context.Context, certificateSigningRequestApproval *certificatesv1alpha1.CertificateSigningRequestApproval, opts v1.UpdateOptions) (*certificatesv1alpha1.CertificateSigningRequestApproval, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, certificateSigningRequestApproval *certificatesv1alpha1.CertificateSigningRequestApproval, opts v1.UpdateOptions) (*certificatesv1alpha1.CertificateSigningRequestApproval, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*certificatesv1alpha1.CertificateSigningRequestApproval, error)
	List(ctx context.Context, opts v1.ListOptions) (*certificatesv1alpha1.CertificateSigningRequestApprovalList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *certificatesv1alpha1.CertificateSigningRequestApproval, err error)
	Apply(ctx context.Context, certificateSigningRequestApproval *applyconfigurationcertificatesv1alpha1.CertificateSigningRequestApprovalApplyConfiguration, opts v1.ApplyOptions) (result *certificatesv1alpha1.CertificateSigningRequestApproval, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, certificateSigningRequestApproval *applyconfigurationcertificatesv1alpha1.CertificateSigningRequestApprovalApplyConfiguration, opts v1.ApplyOptions) (result *certificatesv1alpha1.CertificateSigningRequestApproval, err error)
	CertificateSigningRequestApprovalExpansion
}

// certificateSigningRequestApprovals implements CertificateSigningRequestApprovalInterface
type certificateSigningRequestApprovals struct {
	*gentype.ClientWithListAndApply[*certificatesv1alpha1.CertificateSigningRequestApproval, *certificatesv1alpha1.CertificateSigningRequestApprovalList, *applyconfigurationcertificatesv1alpha1.CertificateSigningRequestApprovalApplyConfiguration]
}

// newCertificateSigningRequestApprovals returns a CertificateSigningRequestApprovals
func newCertificateSigningRequestApprovals(c *CertificatesV1alpha1Client, namespace string) *certificateSigningRequestApprovals {
	return &certificateSigningRequestApprovals{
		gentype.NewClientWithListAndApply[*certificatesv1alpha1.CertificateSigningRequestApproval, *certificatesv1alpha1.CertificateSigningRequestApprovalList, *applyconfigurationcertificatesv1alpha1.CertificateSigningRequestApprovalApplyConfiguration](
			"certificatesigningrequestapprovals",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *certificatesv1alpha1.CertificateSigningRequestApproval {
				return &certificatesv1alpha1.CertificateSigningRequestApproval{}
			},
			func() *certificatesv1alpha1.CertificateSigningRequestApprovalList {
				return &certificatesv1alpha1.CertificateSigningRequestApprovalList{}
			},
		),
	}
}
