# policy.yaml sourced from https://github.com/openshift/cluster-authentication-operator/blob/master/bindata/oauth-openshift/audit-policy.yaml
apiVersion: v1
data:
  policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    rules:
    - level: None
      nonResourceURLs:
      - "/healthz*"
      - "/logs"
      - "/metrics"
      - "/version"
    - level: Metadata
  profile: ""
kind: ConfigMap
metadata:
  name: oauth-openshift-audit
