/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CapacityReservationApplyConfiguration represents a declarative configuration of the CapacityReservation type for use
// with apply.
type CapacityReservationApplyConfiguration struct {
	AvailabilityZone      *string  `json:"availabilityZone,omitempty"`
	EndTime               *v1.Time `json:"endTime,omitempty"`
	ID                    *string  `json:"id,omitempty"`
	InstanceMatchCriteria *string  `json:"instanceMatchCriteria,omitempty"`
	InstanceType          *string  `json:"instanceType,omitempty"`
	OwnerID               *string  `json:"ownerID,omitempty"`
	ReservationType       *string  `json:"reservationType,omitempty"`
	State                 *string  `json:"state,omitempty"`
}

// CapacityReservationApplyConfiguration constructs a declarative configuration of the CapacityReservation type for use with
// apply.
func CapacityReservation() *CapacityReservationApplyConfiguration {
	return &CapacityReservationApplyConfiguration{}
}

// WithAvailabilityZone sets the AvailabilityZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailabilityZone field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithAvailabilityZone(value string) *CapacityReservationApplyConfiguration {
	b.AvailabilityZone = &value
	return b
}

// WithEndTime sets the EndTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndTime field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithEndTime(value v1.Time) *CapacityReservationApplyConfiguration {
	b.EndTime = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithID(value string) *CapacityReservationApplyConfiguration {
	b.ID = &value
	return b
}

// WithInstanceMatchCriteria sets the InstanceMatchCriteria field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceMatchCriteria field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithInstanceMatchCriteria(value string) *CapacityReservationApplyConfiguration {
	b.InstanceMatchCriteria = &value
	return b
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithInstanceType(value string) *CapacityReservationApplyConfiguration {
	b.InstanceType = &value
	return b
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithOwnerID(value string) *CapacityReservationApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithReservationType sets the ReservationType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReservationType field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithReservationType(value string) *CapacityReservationApplyConfiguration {
	b.ReservationType = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *CapacityReservationApplyConfiguration) WithState(value string) *CapacityReservationApplyConfiguration {
	b.State = &value
	return b
}
