/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KubeletConfigurationApplyConfiguration represents a declarative configuration of the KubeletConfiguration type for use
// with apply.
type KubeletConfigurationApplyConfiguration struct {
	RegistryPullQPS                  *int32                 `json:"registryPullQPS,omitempty"`
	RegistryBurst                    *int32                 `json:"registryBurst,omitempty"`
	EventRecordQPS                   *int32                 `json:"eventRecordQPS,omitempty"`
	EventBurst                       *int32                 `json:"eventBurst,omitempty"`
	OOMScoreAdj                      *int32                 `json:"oomScoreAdj,omitempty"`
	StreamingConnectionIdleTimeout   *v1.Duration           `json:"streamingConnectionIdleTimeout,omitempty"`
	NodeStatusUpdateFrequency        *v1.Duration           `json:"nodeStatusUpdateFrequency,omitempty"`
	NodeStatusReportFrequency        *v1.Duration           `json:"nodeStatusReportFrequency,omitempty"`
	ImageMinimumGCAge                *v1.Duration           `json:"imageMinimumGCAge,omitempty"`
	ImageMaximumGCAge                *v1.Duration           `json:"imageMaximumGCAge,omitempty"`
	ImageGCHighThresholdPercent      *int32                 `json:"imageGCHighThresholdPercent,omitempty"`
	ImageGCLowThresholdPercent       *int32                 `json:"imageGCLowThresholdPercent,omitempty"`
	SingleProcessOOMKill             *bool                  `json:"singleProcessOOMKill,omitempty"`
	QOSReserved                      map[string]string      `json:"qosReserved,omitempty"`
	MaxPods                          *int32                 `json:"maxPods,omitempty"`
	PodPidsLimit                     *int64                 `json:"podPidsLimit,omitempty"`
	ResolverConfig                   *string                `json:"resolvConf,omitempty"`
	CPUCFSQuota                      *bool                  `json:"cpuCFSQuota,omitempty"`
	CPUCFSQuotaPeriod                *v1.Duration           `json:"cpuCFSQuotaPeriod,omitempty"`
	NodeStatusMaxImages              *int32                 `json:"nodeStatusMaxImages,omitempty"`
	MaxOpenFiles                     *int64                 `json:"maxOpenFiles,omitempty"`
	KubeAPIQPS                       *int32                 `json:"kubeAPIQPS,omitempty"`
	KubeAPIBurst                     *int32                 `json:"kubeAPIBurst,omitempty"`
	SerializeImagePulls              *bool                  `json:"serializeImagePulls,omitempty"`
	MaxParallelImagePulls            *int32                 `json:"maxParallelImagePulls,omitempty"`
	EvictionHard                     map[string]string      `json:"evictionHard,omitempty"`
	EvictionSoft                     map[string]string      `json:"evictionSoft,omitempty"`
	EvictionSoftGracePeriod          map[string]v1.Duration `json:"evictionSoftGracePeriod,omitempty"`
	EvictionPressureTransitionPeriod *v1.Duration           `json:"evictionPressureTransitionPeriod,omitempty"`
	EvictionMaxPodGracePeriod        *int32                 `json:"evictionMaxPodGracePeriod,omitempty"`
	EvictionMinimumReclaim           map[string]string      `json:"evictionMinimumReclaim,omitempty"`
	PodsPerCore                      *int32                 `json:"podsPerCore,omitempty"`
	EnableControllerAttachDetach     *bool                  `json:"enableControllerAttachDetach,omitempty"`
	ProtectKernelDefaults            *bool                  `json:"protectKernelDefaults,omitempty"`
	FailSwapOn                       *bool                  `json:"failSwapOn,omitempty"`
	ContainerLogMaxSize              *string                `json:"containerLogMaxSize,omitempty"`
	ContainerLogMaxFiles             *int32                 `json:"containerLogMaxFiles,omitempty"`
	ContainerLogMaxWorkers           *int32                 `json:"containerLogMaxWorkers,omitempty"`
	ContainerLogMonitorInterval      *v1.Duration           `json:"containerLogMonitorInterval,omitempty"`
	SystemReserved                   map[string]string      `json:"systemReserved,omitempty"`
	KubeReserved                     map[string]string      `json:"kubeReserved,omitempty"`
	AllowedUnsafeSysctls             []string               `json:"allowedUnsafeSysctls,omitempty"`
	SeccompDefault                   *bool                  `json:"seccompDefault,omitempty"`
	LocalStorageCapacityIsolation    *bool                  `json:"localStorageCapacityIsolation,omitempty"`
}

// KubeletConfigurationApplyConfiguration constructs a declarative configuration of the KubeletConfiguration type for use with
// apply.
func KubeletConfiguration() *KubeletConfigurationApplyConfiguration {
	return &KubeletConfigurationApplyConfiguration{}
}

// WithRegistryPullQPS sets the RegistryPullQPS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegistryPullQPS field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithRegistryPullQPS(value int32) *KubeletConfigurationApplyConfiguration {
	b.RegistryPullQPS = &value
	return b
}

// WithRegistryBurst sets the RegistryBurst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegistryBurst field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithRegistryBurst(value int32) *KubeletConfigurationApplyConfiguration {
	b.RegistryBurst = &value
	return b
}

// WithEventRecordQPS sets the EventRecordQPS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventRecordQPS field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithEventRecordQPS(value int32) *KubeletConfigurationApplyConfiguration {
	b.EventRecordQPS = &value
	return b
}

// WithEventBurst sets the EventBurst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventBurst field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithEventBurst(value int32) *KubeletConfigurationApplyConfiguration {
	b.EventBurst = &value
	return b
}

// WithOOMScoreAdj sets the OOMScoreAdj field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OOMScoreAdj field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithOOMScoreAdj(value int32) *KubeletConfigurationApplyConfiguration {
	b.OOMScoreAdj = &value
	return b
}

// WithStreamingConnectionIdleTimeout sets the StreamingConnectionIdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StreamingConnectionIdleTimeout field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithStreamingConnectionIdleTimeout(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.StreamingConnectionIdleTimeout = &value
	return b
}

// WithNodeStatusUpdateFrequency sets the NodeStatusUpdateFrequency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeStatusUpdateFrequency field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithNodeStatusUpdateFrequency(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.NodeStatusUpdateFrequency = &value
	return b
}

// WithNodeStatusReportFrequency sets the NodeStatusReportFrequency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeStatusReportFrequency field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithNodeStatusReportFrequency(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.NodeStatusReportFrequency = &value
	return b
}

// WithImageMinimumGCAge sets the ImageMinimumGCAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageMinimumGCAge field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithImageMinimumGCAge(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.ImageMinimumGCAge = &value
	return b
}

// WithImageMaximumGCAge sets the ImageMaximumGCAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageMaximumGCAge field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithImageMaximumGCAge(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.ImageMaximumGCAge = &value
	return b
}

// WithImageGCHighThresholdPercent sets the ImageGCHighThresholdPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageGCHighThresholdPercent field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithImageGCHighThresholdPercent(value int32) *KubeletConfigurationApplyConfiguration {
	b.ImageGCHighThresholdPercent = &value
	return b
}

// WithImageGCLowThresholdPercent sets the ImageGCLowThresholdPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageGCLowThresholdPercent field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithImageGCLowThresholdPercent(value int32) *KubeletConfigurationApplyConfiguration {
	b.ImageGCLowThresholdPercent = &value
	return b
}

// WithSingleProcessOOMKill sets the SingleProcessOOMKill field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SingleProcessOOMKill field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithSingleProcessOOMKill(value bool) *KubeletConfigurationApplyConfiguration {
	b.SingleProcessOOMKill = &value
	return b
}

// WithQOSReserved puts the entries into the QOSReserved field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the QOSReserved field,
// overwriting an existing map entries in QOSReserved field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithQOSReserved(entries map[string]string) *KubeletConfigurationApplyConfiguration {
	if b.QOSReserved == nil && len(entries) > 0 {
		b.QOSReserved = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.QOSReserved[k] = v
	}
	return b
}

// WithMaxPods sets the MaxPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPods field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithMaxPods(value int32) *KubeletConfigurationApplyConfiguration {
	b.MaxPods = &value
	return b
}

// WithPodPidsLimit sets the PodPidsLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodPidsLimit field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithPodPidsLimit(value int64) *KubeletConfigurationApplyConfiguration {
	b.PodPidsLimit = &value
	return b
}

// WithResolverConfig sets the ResolverConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResolverConfig field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithResolverConfig(value string) *KubeletConfigurationApplyConfiguration {
	b.ResolverConfig = &value
	return b
}

// WithCPUCFSQuota sets the CPUCFSQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUCFSQuota field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithCPUCFSQuota(value bool) *KubeletConfigurationApplyConfiguration {
	b.CPUCFSQuota = &value
	return b
}

// WithCPUCFSQuotaPeriod sets the CPUCFSQuotaPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUCFSQuotaPeriod field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithCPUCFSQuotaPeriod(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.CPUCFSQuotaPeriod = &value
	return b
}

// WithNodeStatusMaxImages sets the NodeStatusMaxImages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeStatusMaxImages field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithNodeStatusMaxImages(value int32) *KubeletConfigurationApplyConfiguration {
	b.NodeStatusMaxImages = &value
	return b
}

// WithMaxOpenFiles sets the MaxOpenFiles field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxOpenFiles field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithMaxOpenFiles(value int64) *KubeletConfigurationApplyConfiguration {
	b.MaxOpenFiles = &value
	return b
}

// WithKubeAPIQPS sets the KubeAPIQPS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeAPIQPS field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithKubeAPIQPS(value int32) *KubeletConfigurationApplyConfiguration {
	b.KubeAPIQPS = &value
	return b
}

// WithKubeAPIBurst sets the KubeAPIBurst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeAPIBurst field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithKubeAPIBurst(value int32) *KubeletConfigurationApplyConfiguration {
	b.KubeAPIBurst = &value
	return b
}

// WithSerializeImagePulls sets the SerializeImagePulls field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SerializeImagePulls field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithSerializeImagePulls(value bool) *KubeletConfigurationApplyConfiguration {
	b.SerializeImagePulls = &value
	return b
}

// WithMaxParallelImagePulls sets the MaxParallelImagePulls field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxParallelImagePulls field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithMaxParallelImagePulls(value int32) *KubeletConfigurationApplyConfiguration {
	b.MaxParallelImagePulls = &value
	return b
}

// WithEvictionHard puts the entries into the EvictionHard field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EvictionHard field,
// overwriting an existing map entries in EvictionHard field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithEvictionHard(entries map[string]string) *KubeletConfigurationApplyConfiguration {
	if b.EvictionHard == nil && len(entries) > 0 {
		b.EvictionHard = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EvictionHard[k] = v
	}
	return b
}

// WithEvictionSoft puts the entries into the EvictionSoft field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EvictionSoft field,
// overwriting an existing map entries in EvictionSoft field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithEvictionSoft(entries map[string]string) *KubeletConfigurationApplyConfiguration {
	if b.EvictionSoft == nil && len(entries) > 0 {
		b.EvictionSoft = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EvictionSoft[k] = v
	}
	return b
}

// WithEvictionSoftGracePeriod puts the entries into the EvictionSoftGracePeriod field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EvictionSoftGracePeriod field,
// overwriting an existing map entries in EvictionSoftGracePeriod field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithEvictionSoftGracePeriod(entries map[string]v1.Duration) *KubeletConfigurationApplyConfiguration {
	if b.EvictionSoftGracePeriod == nil && len(entries) > 0 {
		b.EvictionSoftGracePeriod = make(map[string]v1.Duration, len(entries))
	}
	for k, v := range entries {
		b.EvictionSoftGracePeriod[k] = v
	}
	return b
}

// WithEvictionPressureTransitionPeriod sets the EvictionPressureTransitionPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionPressureTransitionPeriod field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithEvictionPressureTransitionPeriod(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.EvictionPressureTransitionPeriod = &value
	return b
}

// WithEvictionMaxPodGracePeriod sets the EvictionMaxPodGracePeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionMaxPodGracePeriod field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithEvictionMaxPodGracePeriod(value int32) *KubeletConfigurationApplyConfiguration {
	b.EvictionMaxPodGracePeriod = &value
	return b
}

// WithEvictionMinimumReclaim puts the entries into the EvictionMinimumReclaim field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EvictionMinimumReclaim field,
// overwriting an existing map entries in EvictionMinimumReclaim field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithEvictionMinimumReclaim(entries map[string]string) *KubeletConfigurationApplyConfiguration {
	if b.EvictionMinimumReclaim == nil && len(entries) > 0 {
		b.EvictionMinimumReclaim = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EvictionMinimumReclaim[k] = v
	}
	return b
}

// WithPodsPerCore sets the PodsPerCore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodsPerCore field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithPodsPerCore(value int32) *KubeletConfigurationApplyConfiguration {
	b.PodsPerCore = &value
	return b
}

// WithEnableControllerAttachDetach sets the EnableControllerAttachDetach field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableControllerAttachDetach field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithEnableControllerAttachDetach(value bool) *KubeletConfigurationApplyConfiguration {
	b.EnableControllerAttachDetach = &value
	return b
}

// WithProtectKernelDefaults sets the ProtectKernelDefaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtectKernelDefaults field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithProtectKernelDefaults(value bool) *KubeletConfigurationApplyConfiguration {
	b.ProtectKernelDefaults = &value
	return b
}

// WithFailSwapOn sets the FailSwapOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailSwapOn field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithFailSwapOn(value bool) *KubeletConfigurationApplyConfiguration {
	b.FailSwapOn = &value
	return b
}

// WithContainerLogMaxSize sets the ContainerLogMaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerLogMaxSize field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithContainerLogMaxSize(value string) *KubeletConfigurationApplyConfiguration {
	b.ContainerLogMaxSize = &value
	return b
}

// WithContainerLogMaxFiles sets the ContainerLogMaxFiles field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerLogMaxFiles field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithContainerLogMaxFiles(value int32) *KubeletConfigurationApplyConfiguration {
	b.ContainerLogMaxFiles = &value
	return b
}

// WithContainerLogMaxWorkers sets the ContainerLogMaxWorkers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerLogMaxWorkers field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithContainerLogMaxWorkers(value int32) *KubeletConfigurationApplyConfiguration {
	b.ContainerLogMaxWorkers = &value
	return b
}

// WithContainerLogMonitorInterval sets the ContainerLogMonitorInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerLogMonitorInterval field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithContainerLogMonitorInterval(value v1.Duration) *KubeletConfigurationApplyConfiguration {
	b.ContainerLogMonitorInterval = &value
	return b
}

// WithSystemReserved puts the entries into the SystemReserved field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SystemReserved field,
// overwriting an existing map entries in SystemReserved field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithSystemReserved(entries map[string]string) *KubeletConfigurationApplyConfiguration {
	if b.SystemReserved == nil && len(entries) > 0 {
		b.SystemReserved = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SystemReserved[k] = v
	}
	return b
}

// WithKubeReserved puts the entries into the KubeReserved field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the KubeReserved field,
// overwriting an existing map entries in KubeReserved field with the same key.
func (b *KubeletConfigurationApplyConfiguration) WithKubeReserved(entries map[string]string) *KubeletConfigurationApplyConfiguration {
	if b.KubeReserved == nil && len(entries) > 0 {
		b.KubeReserved = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.KubeReserved[k] = v
	}
	return b
}

// WithAllowedUnsafeSysctls adds the given value to the AllowedUnsafeSysctls field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedUnsafeSysctls field.
func (b *KubeletConfigurationApplyConfiguration) WithAllowedUnsafeSysctls(values ...string) *KubeletConfigurationApplyConfiguration {
	for i := range values {
		b.AllowedUnsafeSysctls = append(b.AllowedUnsafeSysctls, values[i])
	}
	return b
}

// WithSeccompDefault sets the SeccompDefault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeccompDefault field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithSeccompDefault(value bool) *KubeletConfigurationApplyConfiguration {
	b.SeccompDefault = &value
	return b
}

// WithLocalStorageCapacityIsolation sets the LocalStorageCapacityIsolation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalStorageCapacityIsolation field is set to the value of the last call.
func (b *KubeletConfigurationApplyConfiguration) WithLocalStorageCapacityIsolation(value bool) *KubeletConfigurationApplyConfiguration {
	b.LocalStorageCapacityIsolation = &value
	return b
}
