/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	karpenterv1beta1 "github.com/openshift/hypershift/api/karpenter/v1beta1"
)

// MetadataOptionsApplyConfiguration represents a declarative configuration of the MetadataOptions type for use
// with apply.
type MetadataOptionsApplyConfiguration struct {
	HTTPEndpoint            *karpenterv1beta1.MetadataEndpointState     `json:"httpEndpoint,omitempty"`
	HTTPProtocolIPv6        *karpenterv1beta1.MetadataProtocolIPv6State `json:"httpProtocolIPv6,omitempty"`
	HTTPPutResponseHopLimit *int64                                      `json:"httpPutResponseHopLimit,omitempty"`
	HTTPTokens              *karpenterv1beta1.MetadataHTTPTokensState   `json:"httpTokens,omitempty"`
}

// MetadataOptionsApplyConfiguration constructs a declarative configuration of the MetadataOptions type for use with
// apply.
func MetadataOptions() *MetadataOptionsApplyConfiguration {
	return &MetadataOptionsApplyConfiguration{}
}

// WithHTTPEndpoint sets the HTTPEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPEndpoint field is set to the value of the last call.
func (b *MetadataOptionsApplyConfiguration) WithHTTPEndpoint(value karpenterv1beta1.MetadataEndpointState) *MetadataOptionsApplyConfiguration {
	b.HTTPEndpoint = &value
	return b
}

// WithHTTPProtocolIPv6 sets the HTTPProtocolIPv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPProtocolIPv6 field is set to the value of the last call.
func (b *MetadataOptionsApplyConfiguration) WithHTTPProtocolIPv6(value karpenterv1beta1.MetadataProtocolIPv6State) *MetadataOptionsApplyConfiguration {
	b.HTTPProtocolIPv6 = &value
	return b
}

// WithHTTPPutResponseHopLimit sets the HTTPPutResponseHopLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPPutResponseHopLimit field is set to the value of the last call.
func (b *MetadataOptionsApplyConfiguration) WithHTTPPutResponseHopLimit(value int64) *MetadataOptionsApplyConfiguration {
	b.HTTPPutResponseHopLimit = &value
	return b
}

// WithHTTPTokens sets the HTTPTokens field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPTokens field is set to the value of the last call.
func (b *MetadataOptionsApplyConfiguration) WithHTTPTokens(value karpenterv1beta1.MetadataHTTPTokensState) *MetadataOptionsApplyConfiguration {
	b.HTTPTokens = &value
	return b
}
