apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-version-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cluster-version-operator
  template:
    metadata:
      name: cluster-version-operator
      labels:
        k8s-app: cluster-version-operator
        clusterID: "{{ .ClusterID }}"
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      imagePullSecrets:
      - name: pull-secret
      automountServiceAccountToken: false
      initContainers:
      - name: prepare-payload
        image: {{ .ReleaseImage }}
        imagePullPolicy: Always
        command:
        - /bin/bash
        args:
        - -c
        - |-
          cp -R /manifests /var/payload/
          cp -R /release-manifests /var/payload/
          # Delete any manifests you want to exclude from /var/payload/release-manifests
          # ie. rm /var/payload/release-manifests/0000_50_olm_07-olm-operator.deployment.yaml

          # rm /var/payload/release-manifests/0000_50_olm_00-namespace.yaml
          rm /var/payload/release-manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
          rm /var/payload/release-manifests/0000_50_olm_02-services.yaml
          rm /var/payload/release-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
          rm /var/payload/release-manifests/0000_50_olm_07-olm-operator.deployment.yaml
          rm /var/payload/release-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
          rm /var/payload/release-manifests/0000_50_olm_08-catalog-operator.deployment.yaml
          rm /var/payload/release-manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
          rm /var/payload/release-manifests/0000_50_olm_99-operatorstatus.yaml
          rm /var/payload/release-manifests/0000_90_olm_00-service-monitor.yaml
          rm /var/payload/release-manifests/0000_90_olm_01-prometheus-rule.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_04_service_account.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_05_role.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_06_role_binding.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_07_configmap.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_08_service.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_09_operator-ibm-cloud-managed.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_09_operator.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_10_clusteroperator.yaml
          rm /var/payload/release-manifests/0000_50_operator-marketplace_11_service_monitor.yaml
        volumeMounts:
        - name: payload
          mountPath: /var/payload
      containers:
        - name: cluster-version-operator
          image: {{ .ReleaseImage }}
          imagePullPolicy: Always
          command:
            - "cluster-version-operator"
          args:
            - "start"
            - "--release-image={{ .ReleaseImage }}"
            - "--enable-auto-update=false"
            - "--enable-default-cluster-version=true"
            - "--kubeconfig=/etc/openshift/kubeconfig/kubeconfig"
            - "--listen="
            - "--v=4"
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/cvo/updatepayloads
              name: etc-cvo-updatepayloads
              readOnly: true
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
            - mountPath: /var/payload
              name: payload
          env:
            - name: PAYLOAD_OVERRIDE
              value: /var/payload
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: EXCLUDE_MANIFESTS
              value: internal-openshift-hosted
{{ if .ROKSMetricsImage }}
        - name: metrics-pusher
          image: {{ .ROKSMetricsImage }}
          imagePullPolicy: Always
          command:
            - "metrics-pusher"
          args:
            - "--destination-path=/api/v1/namespaces/openshift-roks-metrics/services/push-gateway:http/proxy/metrics/job/cluster-version-operator"
            - "--kubeconfig=/etc/openshift/kubeconfig/kubeconfig"
            - "--frequency=30s"
            - "--source-url=http://localhost:9099/metrics"
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
{{ end }}
      volumes:
        - name: work
          emptyDir: {}
        - name: etc-cvo-updatepayloads
          emptyDir: {}
        - name: kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig
        - name: payload
          emptyDir: {}
