apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpo-sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpo-sleeper
  template:
    metadata:
      labels:
        app: cpo-sleeper
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: sleeper
        image: cli
        command:
        - /bin/bash
        - -c
        - sleep infinity
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
