apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: certificatesigningrequestapprovals.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: CertificateSigningRequestApproval
    listKind: CertificateSigningRequestApprovalList
    plural: certificatesigningrequestapprovals
    shortNames:
    - csra
    - csras
    singular: certificatesigningrequestapproval
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
