apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/GCPPlatform: "true"
  name: gcpprivateserviceconnects.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: GCPPrivateServiceConnect
    listKind: GCPPrivateServiceConnectList
    plural: gcpprivateserviceconnects
    shortNames:
    - gcppsc
    singular: gcpprivateserviceconnect
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the Service Attachment
      jsonPath: .status.serviceAttachmentName
      name: Service Attachment
      type: string
    - description: IP address of the PSC endpoint
      jsonPath: .status.endpointIP
      name: Endpoint IP
      type: string
    - description: Overall PSC readiness status
      jsonPath: .status.conditions[?(@.type=="GCPPrivateServiceConnectReady")].status
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: GCPPrivateServiceConnect represents GCP Private Service Connect
          infrastructure
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec is the specification for the GCPPrivateServiceConnect.
            properties:
              consumerAcceptList:
                description: |-
                  consumerAcceptList specifies which customer projects can connect
                  Accepts both project IDs (e.g. "my-project-123") and project numbers (e.g. "123456789012")
                items:
                  maxLength: 30
                  pattern: ^([a-z][a-z0-9-]{4,28}[a-z0-9]|[0-9]{6,12})$
                  type: string
                maxItems: 50
                minItems: 1
                type: array
              forwardingRuleName:
                description: forwardingRuleName is the name of the Internal Load Balancer
                  forwarding rule
                maxLength: 63
                minLength: 1
                pattern: ^[a-z]([-a-z0-9]*[a-z0-9])?$
                type: string
              natSubnet:
                description: |-
                  natSubnet is the subnet used for NAT by the Service Attachment
                  Auto-populated by the Hypershift Operator (implementation out of scope)
                maxLength: 63
                pattern: ^[a-z]([-a-z0-9]*[a-z0-9])?$
                type: string
            required:
            - consumerAcceptList
            - forwardingRuleName
            type: object
          status:
            description: status is the status of the GCPPrivateServiceConnect.
            properties:
              conditions:
                description: |-
                  conditions represent the current state of PSC infrastructure
                  Current condition types are: "GCPPrivateServiceConnectReady", "GCPServiceAttachmentReady", "GCPEndpointReady", "GCPDNSReady"
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                maxItems: 10
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              dnsRecords:
                description: dnsRecords lists the created DNS A records
                items:
                  maxLength: 253
                  type: string
                maxItems: 10
                type: array
              dnsZoneName:
                description: dnsZoneName is the private DNS zone name
                maxLength: 253
                type: string
              endpointIP:
                description: endpointIP is the reserved IP address for the PSC endpoint
                maxLength: 15
                pattern: ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
                type: string
              serviceAttachmentName:
                description: serviceAttachmentName is the name of the created Service
                  Attachment
                maxLength: 63
                type: string
              serviceAttachmentURI:
                description: |-
                  serviceAttachmentURI is the URI customers use to connect
                  Format: projects/{project}/regions/{region}/serviceAttachments/{name}
                maxLength: 2048
                pattern: ^projects/[a-z][a-z0-9-]{4,28}[a-z0-9]/regions/[a-z]+-[a-z0-9]+[0-9]/serviceAttachments/[a-z]([-a-z0-9]*[a-z0-9])?$
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
