apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: kubevirt-cloud-controller-manager
