#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")
CODEGEN_PKG=${CODEGEN_PKG:-$(cd "${SCRIPT_ROOT}"; ls -d -1 ./tools/vendor/k8s.io/code-generator 2>/dev/null)}

source "${SCRIPT_ROOT}/${CODEGEN_PKG}/kube_codegen.sh"

# TODO: remove the workaround when the issue is solved in the code-generator
# (https://github.com/kubernetes/code-generator/issues/165).
PROJECT_ROOT=$(realpath $(dirname ${BASH_SOURCE[0]})/..)
mkdir -p ${PROJECT_ROOT}/github.com/openshift
ln -s ${PROJECT_ROOT} github.com/openshift
trap "rm -rf ${PROJECT_ROOT}/github.com" EXIT

# Deep-copies and what-not are generated by controller-gen, so we don't need to use kube::codegen::gen_helpers

kube::codegen::gen_client \
    --with-watch \
    --with-applyconfig \
    --input-pkg-root github.com/openshift/hypershift/api \
    --output-pkg-root github.com/openshift/hypershift/client \
    --output-base "$(dirname "${BASH_SOURCE[0]}")/.." \
    --versioned-name clientset \
    --boilerplate "${SCRIPT_ROOT}/boilerplate.go.txt"