#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")
# Prefer vendored code-generator if present; otherwise, resolve from hack/tools module
CODEGEN_PKG=${CODEGEN_PKG:-$(cd "${SCRIPT_ROOT}"; ls -d -1 ./tools/vendor/k8s.io/code-generator 2>/dev/null || true)}
if [[ -z "${CODEGEN_PKG}" ]]; then
  # Note: -C must come right after 'go'
  CODEGEN_PKG=$(GO111MODULE=on GOWORK=off GOFLAGS=-mod=mod go -C "${SCRIPT_ROOT}/tools" list -m -f '{{.Dir}}' k8s.io/code-generator)
fi

# When CODEGEN_PKG is an absolute path, source directly; otherwise, join with SCRIPT_ROOT
if [[ "${CODEGEN_PKG}" = /* ]]; then
  source "${CODEGEN_PKG}/kube_codegen.sh"
else
  source "${SCRIPT_ROOT}/${CODEGEN_PKG}/kube_codegen.sh"
fi

# Deep-copies and what-not are generated by controller-gen, so we don't need to use kube::codegen::gen_helpers
cd "${SCRIPT_ROOT}/../api"

kube::codegen::gen_client \
    --with-watch \
    --with-applyconfig \
    --output-dir ../client \
    --output-pkg github.com/openshift/hypershift/client \
    --versioned-name clientset \
    --boilerplate "../${SCRIPT_ROOT}/boilerplate.go.txt" \
    .