/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	applyconfigurationhypershiftv1beta1 "github.com/openshift/hypershift/client/applyconfiguration/hypershift/v1beta1"
	scheme "github.com/openshift/hypershift/client/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HostedClustersGetter has a method to return a HostedClusterInterface.
// A group's client should implement this interface.
type HostedClustersGetter interface {
	HostedClusters(namespace string) HostedClusterInterface
}

// HostedClusterInterface has methods to work with HostedCluster resources.
type HostedClusterInterface interface {
	Create(ctx context.Context, hostedCluster *hypershiftv1beta1.HostedCluster, opts v1.CreateOptions) (*hypershiftv1beta1.HostedCluster, error)
	Update(ctx context.Context, hostedCluster *hypershiftv1beta1.HostedCluster, opts v1.UpdateOptions) (*hypershiftv1beta1.HostedCluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hostedCluster *hypershiftv1beta1.HostedCluster, opts v1.UpdateOptions) (*hypershiftv1beta1.HostedCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*hypershiftv1beta1.HostedCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*hypershiftv1beta1.HostedClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hypershiftv1beta1.HostedCluster, err error)
	Apply(ctx context.Context, hostedCluster *applyconfigurationhypershiftv1beta1.HostedClusterApplyConfiguration, opts v1.ApplyOptions) (result *hypershiftv1beta1.HostedCluster, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, hostedCluster *applyconfigurationhypershiftv1beta1.HostedClusterApplyConfiguration, opts v1.ApplyOptions) (result *hypershiftv1beta1.HostedCluster, err error)
	HostedClusterExpansion
}

// hostedClusters implements HostedClusterInterface
type hostedClusters struct {
	*gentype.ClientWithListAndApply[*hypershiftv1beta1.HostedCluster, *hypershiftv1beta1.HostedClusterList, *applyconfigurationhypershiftv1beta1.HostedClusterApplyConfiguration]
}

// newHostedClusters returns a HostedClusters
func newHostedClusters(c *HypershiftV1beta1Client, namespace string) *hostedClusters {
	return &hostedClusters{
		gentype.NewClientWithListAndApply[*hypershiftv1beta1.HostedCluster, *hypershiftv1beta1.HostedClusterList, *applyconfigurationhypershiftv1beta1.HostedClusterApplyConfiguration](
			"hostedclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *hypershiftv1beta1.HostedCluster { return &hypershiftv1beta1.HostedCluster{} },
			func() *hypershiftv1beta1.HostedClusterList { return &hypershiftv1beta1.HostedClusterList{} },
		),
	}
}
