apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/DynamicResourceAllocation: "true"
  name: hostedcontrolplanes.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    categories:
    - cluster-api
    kind: HostedControlPlane
    listKind: HostedControlPlaneList
    plural: hostedcontrolplanes
    shortNames:
    - hcp
    - hcps
    singular: hostedcontrolplane
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
