apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-network-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  - monitoring.rhobs
  resources:
  - servicemonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes/status
  verbs:
  - '*'
