apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-storage-version-migrator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kube-storage-version-migrator
  template:
    metadata:
      labels:
        app: kube-storage-version-migrator
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
      containers:
      - name: migrator
        image: kube-storage-version-migrator
        command:
          - migrator
        args:
          - '--alsologtostderr'
          - '--v=2'
          - '--kubeconfig=/etc/kubernetes/kubeconfig'
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes
          readOnly: true
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
