apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller-manager
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: cloud-controller-manager
    spec:
      containers:
      - command:
        - /bin/ibm-cloud-controller-manager
        - --authentication-skip-lookup
        - --bind-address=$(POD_IP_ADDRESS)
        - --use-service-account-credentials=true
        - --configure-cloud-routes=false
        - --cloud-provider=ibm
        - --cloud-config=/etc/ibm/ccm-config
        - --profiling=false
        - --leader-elect=true
        - --leader-elect-lease-duration=137s
        - --leader-elect-renew-deadline=107s
        - --leader-elect-retry-period=26s
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_256_GCM_SHA384
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --use-service-account-credentials=false
        env:
        - name: POD_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VPCCTL_CLOUD_CONFIG
          value: /etc/ibm/ccm-config
        - name: ENABLE_VPC_PUBLIC_ENDPOINT
          value: "true"
        image: powervs-cloud-controller-manager
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10258
            scheme: HTTPS
          initialDelaySeconds: 300
          timeoutSeconds: 5
        name: cloud-controller-manager
        ports:
        - containerPort: 10258
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 75m
            memory: 60Mi
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: service-network-admin-kubeconfig
        - mountPath: /etc/ibm
          name: ccm-config
        - mountPath: /etc/vpc
          name: cloud-creds
      terminationGracePeriodSeconds: 90
      volumes:
      - name: service-network-admin-kubeconfig
        secret:
          defaultMode: 416
          secretName: service-network-admin-kubeconfig
      - configMap:
          defaultMode: 420
          name: ccm-config
        name: ccm-config
      - name: cloud-creds
        secret:
          defaultMode: 416
          secretName: hcp.Spec.Platform.PowerVS.KubeCloudControllerCreds.Name
