apiVersion: v1
kind: ConfigMap
metadata:
  name: ignition-server-proxy-config
data:
  haproxy.conf: |
    defaults
      mode http
      timeout connect 5s
      timeout client 30s
      timeout server 30s

    frontend ignition-server
      bind :::8443 v4v6 ssl crt /tmp/tls.pem alpn http/1.1
      default_backend ignition_servers

    backend ignition_servers
      server ignition-server ignition-server:443 check ssl ca-file /etc/ssl/root-ca/ca.crt alpn http/1.1
