apiVersion: v1
data:
  config.yaml: |
    admission: {}
    aggregatorConfig:
      allowedNames: null
      clientCA: ""
      extraHeaderPrefixes: null
      groupHeaders: null
      usernameHeaders: null
    apiServerArguments:
      audit-log-format:
      - json
      audit-log-maxbackup:
      - "1"
      audit-log-maxsize:
      - "10"
      audit-log-path:
      - /var/log/openshift-apiserver/audit.log
      audit-policy-file:
      - /etc/kubernetes/audit-config/policy.yaml
      shutdown-delay-duration:
      - 15s
    apiServers:
      perGroupOptions: null
    apiVersion: openshiftcontrolplane.config.openshift.io/v1
    auditConfig:
      auditFilePath: ""
      enabled: false
      logFormat: ""
      maximumFileRetentionDays: 0
      maximumFileSizeMegabytes: 0
      maximumRetainedFiles: 0
      policyConfiguration: null
      policyFile: ""
      webHookKubeConfig: ""
      webHookMode: ""
    cloudProviderFile: ""
    corsAllowedOrigins: null
    imagePolicyConfig:
      additionalTrustedCA: ""
      allowedRegistriesForImport: null
      externalRegistryHostnames: null
      internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
      maxImagesBulkImportedPerRepository: 0
    jenkinsPipelineConfig:
      autoProvisionEnabled: null
      parameters: null
      serviceName: ""
      templateName: ""
      templateNamespace: ""
    kind: OpenShiftAPIServerConfig
    kubeClientConfig:
      connectionOverrides:
        acceptContentTypes: ""
        burst: 0
        contentType: ""
        qps: 0
      kubeConfig: /etc/kubernetes/secrets/svc-kubeconfig/kubeconfig
    projectConfig:
      defaultNodeSelector: ""
      projectRequestTemplate: ""
    routingConfig:
      subdomain: ""
    serviceAccountOAuthGrantMethod: ""
    servingInfo:
      bindAddress: ""
      bindNetwork: ""
      certFile: /etc/kubernetes/certs/serving/tls.crt
      clientCA: /etc/kubernetes/certs/client-ca/ca.crt
      keyFile: /etc/kubernetes/certs/serving/tls.key
      maxRequestsInFlight: 0
      requestTimeoutSeconds: 0
    storageConfig:
      ca: /etc/kubernetes/certs/etcd-client-ca/ca.crt
      certFile: /etc/kubernetes/certs/etcd-client/etcd-client.crt
      keyFile: /etc/kubernetes/certs/etcd-client/etcd-client.key
      storagePrefix: ""
      urls:
      - https://etcd-client:2379
kind: ConfigMap
metadata:
  name: openshift-apiserver
