package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func init() {
	SchemeBuilder.Register(&PlatformConfiguration{}, &PlatformConfigurationList{})
}

const (
	PlatformBeingConfigured         = "PlatformInfrastructureBeingConfigured"
	PlatformConfiguredAsExpected    = "PlatformInfrastructureConfiguredAsExpected"
	PlatfromDestroy                 = "PlatformInfrastructureDestroy"
	PlatformMisConfiguredReason     = "PlatformInfrastructureMisconfigured"
	PlatformIAMBeingConfigured      = "PlatformIAMBeingConfigured"
	PlatformIAMConfiguredAsExpected = "PlatformIAMConfiguredAsExpected"
	PlatformIAMRemove               = "PlatformIAMRemove"
	PlatformIAMMisConfiguredReason  = "PlatformIAMMisconfigured"

	// PlatformConfigured indicates (if status is true) that the
	// platform configuration specified for the platform provider has been deployed
	PlatformConfigured    ConditionType = "PlatformInfrastructureConfigured"
	PlatformIAMConfigured ConditionType = "PlatformIAMConfigured"
)

// ProviderPlatformSpec defines the desired state of HostedCluster
type PlatformConfigurationSpec struct {

	// PullSecret is a pull secret injected into the container runtime of guest
	// workers. It should have an ".dockerconfigjson" key containing the pull secret JSON.
	// +immutable
	PullSecret corev1.LocalObjectReference `json:"pullSecret"`

	// SSHKey is a reference to a Secret containing a single key "id_rsa.pub",
	// whose value is the public part of an SSH key that can be used to access
	// Nodes.
	// +immutable
	SSHKey corev1.LocalObjectReference `json:"sshKey,omitempty"`

	// Networking contains network-specific settings for this cluster
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	Networking PlatformClusterNetworking `json:"networking,omitempty"`

	// +immutable
	Platform PlatformSpec `json:"platform"`

	// DNS configuration for the cluster
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	DNS DNSSpec `json:"dns"`

	// +kubebuilder:default:="https://kubernetes.default.svc"
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	IssuerURL string `json:"issuerURL"`

	// InfraID is used to identify the cluster related Platform Configurations in a provider
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	// +optional
	InfraID string `json:"infraID,omitempty"`

	// PlatformSecurity contains IAM related information for the provider
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	// +optional
	IAM PlatformSecurity `json:"iam,omitempty"`
}

type PlatformSecurity struct {

	// SecurityGroups is the set of security groups to associate with nodepool machines
	// +optional
	SecurityGroups []AWSResourceReference `json:"securityGroups,omitempty"`

	// InstanceProfile is the AWS provider profile name
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	// +optional
	InstanceProfile string `json:"instanceProfile,omitempty"`

	// OIDCProvider is the ARN use for this hypershift instance
	// Auto-generated by the PlatformConfiguration controller
	// +immutable
	// +optional
	OIDCProvider string `json:"oidcProvider,omitempty"`
}

// ClusterNetworking specifies network configuration for a cluster.
type PlatformClusterNetworking struct {

	// MachineCIDR is...
	//
	// Private Subnet ID.
	//
	// +immutable
	MachineCIDR string `json:"machineCIDR"`
}

type PlatformConfigurationStatus struct {
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +genclient

// PlatformConfiguration is the primary representation of a HyperShift cluster and encapsulates
// the control plane and common data plane configuration. Creating a PlatformConfiguration
// results in a fully functional OpenShift control plane with no attached nodes.
// To support workloads (e.g. pods), a PlatformConfiguration may have one or more associated
// NodePool resources.
//
// +kubebuilder:object:root=true
// +kubebuilder:resource:path=platformconfiguration,shortName=pcg;pcgs,scope=Namespaced
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="INFRA Ready",type="string",JSONPath=".status.conditions[?(@.type==\"PlatformInfrastructureConfigured\")].status",description="Configured"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type==\"PlatformInfrastructureConfigured\")].reason",description="Reason"
// +kubebuilder:printcolumn:name="IAM Ready",type="string",JSONPath=".status.conditions[?(@.type==\"PlatformIAMConfigured\")].status",description="Configured"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type==\"PlatformIAMConfigured\")].reason",description="Reason"
type PlatformConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec is the desired behavior of the PlatformConfiguration.
	Spec PlatformConfigurationSpec `json:"spec"`

	// Status is the latest observed status of the PlatformConfiguration.
	Status PlatformConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// PlatformConfigurationList contains a list of PlatformConfiguration
type PlatformConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PlatformConfiguration `json:"items"`
}
