/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AddressPairApplyConfiguration represents a declarative configuration of the AddressPair type for use
// with apply.
type AddressPairApplyConfiguration struct {
	IPAddress *string `json:"ipAddress,omitempty"`
}

// AddressPairApplyConfiguration constructs a declarative configuration of the AddressPair type for use with
// apply.
func AddressPair() *AddressPairApplyConfiguration {
	return &AddressPairApplyConfiguration{}
}

// WithIPAddress sets the IPAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAddress field is set to the value of the last call.
func (b *AddressPairApplyConfiguration) WithIPAddress(value string) *AddressPairApplyConfiguration {
	b.IPAddress = &value
	return b
}
