/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// AESCBCKeyStatusApplyConfiguration represents a declarative configuration of the AESCBCKeyStatus type for use
// with apply.
type AESCBCKeyStatusApplyConfiguration struct {
	Secret   *v1.LocalObjectReference `json:"secret,omitempty"`
	DataHash *string                  `json:"dataHash,omitempty"`
}

// AESCBCKeyStatusApplyConfiguration constructs a declarative configuration of the AESCBCKeyStatus type for use with
// apply.
func AESCBCKeyStatus() *AESCBCKeyStatusApplyConfiguration {
	return &AESCBCKeyStatusApplyConfiguration{}
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *AESCBCKeyStatusApplyConfiguration) WithSecret(value v1.LocalObjectReference) *AESCBCKeyStatusApplyConfiguration {
	b.Secret = &value
	return b
}

// WithDataHash sets the DataHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataHash field is set to the value of the last call.
func (b *AESCBCKeyStatusApplyConfiguration) WithDataHash(value string) *AESCBCKeyStatusApplyConfiguration {
	b.DataHash = &value
	return b
}
