/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AutoRepairSettingsApplyConfiguration represents an declarative configuration of the AutoRepairSettings type for use
// with apply.
type AutoRepairSettingsApplyConfiguration struct {
	NodeStartupTimeout  *v1.Duration                           `json:"nodeStartupTimeout,omitempty"`
	UnhealthyConditions []UnhealthyConditionApplyConfiguration `json:"unhealthyConditions,omitempty"`
}

// AutoRepairSettingsApplyConfiguration constructs an declarative configuration of the AutoRepairSettings type for use with
// apply.
func AutoRepairSettings() *AutoRepairSettingsApplyConfiguration {
	return &AutoRepairSettingsApplyConfiguration{}
}

// WithNodeStartupTimeout sets the NodeStartupTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeStartupTimeout field is set to the value of the last call.
func (b *AutoRepairSettingsApplyConfiguration) WithNodeStartupTimeout(value v1.Duration) *AutoRepairSettingsApplyConfiguration {
	b.NodeStartupTimeout = &value
	return b
}

// WithUnhealthyConditions adds the given value to the UnhealthyConditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UnhealthyConditions field.
func (b *AutoRepairSettingsApplyConfiguration) WithUnhealthyConditions(values ...*UnhealthyConditionApplyConfiguration) *AutoRepairSettingsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUnhealthyConditions")
		}
		b.UnhealthyConditions = append(b.UnhealthyConditions, *values[i])
	}
	return b
}
