/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AWSManagedDNSSpecApplyConfiguration represents a declarative configuration of the AWSManagedDNSSpec type for use
// with apply.
type AWSManagedDNSSpecApplyConfiguration struct {
	IngressDomainPrefix *string                                        `json:"ingressDomainPrefix,omitempty"`
	Delegation          *AWSManagedDNSDelegationSpecApplyConfiguration `json:"delegation,omitempty"`
}

// AWSManagedDNSSpecApplyConfiguration constructs a declarative configuration of the AWSManagedDNSSpec type for use with
// apply.
func AWSManagedDNSSpec() *AWSManagedDNSSpecApplyConfiguration {
	return &AWSManagedDNSSpecApplyConfiguration{}
}

// WithIngressDomainPrefix sets the IngressDomainPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressDomainPrefix field is set to the value of the last call.
func (b *AWSManagedDNSSpecApplyConfiguration) WithIngressDomainPrefix(value string) *AWSManagedDNSSpecApplyConfiguration {
	b.IngressDomainPrefix = &value
	return b
}

// WithDelegation sets the Delegation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delegation field is set to the value of the last call.
func (b *AWSManagedDNSSpecApplyConfiguration) WithDelegation(value *AWSManagedDNSDelegationSpecApplyConfiguration) *AWSManagedDNSSpecApplyConfiguration {
	b.Delegation = value
	return b
}
