/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AWSSharedVPCApplyConfiguration represents a declarative configuration of the AWSSharedVPC type for use
// with apply.
type AWSSharedVPCApplyConfiguration struct {
	RolesRef    *AWSSharedVPCRolesRefApplyConfiguration `json:"rolesRef,omitempty"`
	LocalZoneID *string                                 `json:"localZoneID,omitempty"`
}

// AWSSharedVPCApplyConfiguration constructs a declarative configuration of the AWSSharedVPC type for use with
// apply.
func AWSSharedVPC() *AWSSharedVPCApplyConfiguration {
	return &AWSSharedVPCApplyConfiguration{}
}

// WithRolesRef sets the RolesRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RolesRef field is set to the value of the last call.
func (b *AWSSharedVPCApplyConfiguration) WithRolesRef(value *AWSSharedVPCRolesRefApplyConfiguration) *AWSSharedVPCApplyConfiguration {
	b.RolesRef = value
	return b
}

// WithLocalZoneID sets the LocalZoneID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalZoneID field is set to the value of the last call.
func (b *AWSSharedVPCApplyConfiguration) WithLocalZoneID(value string) *AWSSharedVPCApplyConfiguration {
	b.LocalZoneID = &value
	return b
}
