/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AzurePlatformSpecApplyConfiguration represents an declarative configuration of the AzurePlatformSpec type for use
// with apply.
type AzurePlatformSpecApplyConfiguration struct {
	TenantID                     *string `json:"tenantID,omitempty"`
	Cloud                        *string `json:"cloud,omitempty"`
	Location                     *string `json:"location,omitempty"`
	ResourceGroupName            *string `json:"resourceGroup,omitempty"`
	VnetID                       *string `json:"vnetID,omitempty"`
	SubnetID                     *string `json:"subnetID,omitempty"`
	SubscriptionID               *string `json:"subscriptionID,omitempty"`
	MachineIdentityID            *string `json:"machineIdentityID,omitempty"`
	SecurityGroupID              *string `json:"securityGroupID,omitempty"`
	IngressClientID              *string `json:"ingressClientID,omitempty"`
	ImageRegistryClientID        *string `json:"imageRegistryClientID,omitempty"`
	DiskClientID                 *string `json:"diskClientID,omitempty"`
	FileClientID                 *string `json:"fileClientID,omitempty"`
	NetworkClientID              *string `json:"networkClientID,omitempty"`
	KubeCloudControllerClientID  *string `json:"kubeCloudControllerClientID,omitempty"`
	NodePoolManagementClientID   *string `json:"nodePoolManagementClientID,omitempty"`
	ControlPlaneOperatorClientID *string `json:"controlPlaneOperatorClientID,omitempty"`
}

// AzurePlatformSpecApplyConfiguration constructs an declarative configuration of the AzurePlatformSpec type for use with
// apply.
func AzurePlatformSpec() *AzurePlatformSpecApplyConfiguration {
	return &AzurePlatformSpecApplyConfiguration{}
}

// WithTenantID sets the TenantID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithTenantID(value string) *AzurePlatformSpecApplyConfiguration {
	b.TenantID = &value
	return b
}

// WithCloud sets the Cloud field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cloud field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithCloud(value string) *AzurePlatformSpecApplyConfiguration {
	b.Cloud = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithLocation(value string) *AzurePlatformSpecApplyConfiguration {
	b.Location = &value
	return b
}

// WithResourceGroupName sets the ResourceGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceGroupName field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithResourceGroupName(value string) *AzurePlatformSpecApplyConfiguration {
	b.ResourceGroupName = &value
	return b
}

// WithVnetID sets the VnetID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VnetID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithVnetID(value string) *AzurePlatformSpecApplyConfiguration {
	b.VnetID = &value
	return b
}

// WithSubnetID sets the SubnetID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubnetID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithSubnetID(value string) *AzurePlatformSpecApplyConfiguration {
	b.SubnetID = &value
	return b
}

// WithSubscriptionID sets the SubscriptionID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubscriptionID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithSubscriptionID(value string) *AzurePlatformSpecApplyConfiguration {
	b.SubscriptionID = &value
	return b
}

// WithMachineIdentityID sets the MachineIdentityID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineIdentityID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithMachineIdentityID(value string) *AzurePlatformSpecApplyConfiguration {
	b.MachineIdentityID = &value
	return b
}

// WithSecurityGroupID sets the SecurityGroupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityGroupID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithSecurityGroupID(value string) *AzurePlatformSpecApplyConfiguration {
	b.SecurityGroupID = &value
	return b
}

// WithIngressClientID sets the IngressClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithIngressClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.IngressClientID = &value
	return b
}

// WithImageRegistryClientID sets the ImageRegistryClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageRegistryClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithImageRegistryClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.ImageRegistryClientID = &value
	return b
}

// WithDiskClientID sets the DiskClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithDiskClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.DiskClientID = &value
	return b
}

// WithFileClientID sets the FileClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FileClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithFileClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.FileClientID = &value
	return b
}

// WithNetworkClientID sets the NetworkClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithNetworkClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.NetworkClientID = &value
	return b
}

// WithKubeCloudControllerClientID sets the KubeCloudControllerClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeCloudControllerClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithKubeCloudControllerClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.KubeCloudControllerClientID = &value
	return b
}

// WithNodePoolManagementClientID sets the NodePoolManagementClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePoolManagementClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithNodePoolManagementClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.NodePoolManagementClientID = &value
	return b
}

// WithControlPlaneOperatorClientID sets the ControlPlaneOperatorClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlaneOperatorClientID field is set to the value of the last call.
func (b *AzurePlatformSpecApplyConfiguration) WithControlPlaneOperatorClientID(value string) *AzurePlatformSpecApplyConfiguration {
	b.ControlPlaneOperatorClientID = &value
	return b
}
