/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AzurePrivateLinkSpecApplyConfiguration represents a declarative configuration of the AzurePrivateLinkSpec type for use
// with apply.
type AzurePrivateLinkSpecApplyConfiguration struct {
	NATSubnetID                    *string  `json:"natSubnetID,omitempty"`
	AdditionalAllowedSubscriptions []string `json:"additionalAllowedSubscriptions,omitempty"`
}

// AzurePrivateLinkSpecApplyConfiguration constructs a declarative configuration of the AzurePrivateLinkSpec type for use with
// apply.
func AzurePrivateLinkSpec() *AzurePrivateLinkSpecApplyConfiguration {
	return &AzurePrivateLinkSpecApplyConfiguration{}
}

// WithNATSubnetID sets the NATSubnetID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NATSubnetID field is set to the value of the last call.
func (b *AzurePrivateLinkSpecApplyConfiguration) WithNATSubnetID(value string) *AzurePrivateLinkSpecApplyConfiguration {
	b.NATSubnetID = &value
	return b
}

// WithAdditionalAllowedSubscriptions adds the given value to the AdditionalAllowedSubscriptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalAllowedSubscriptions field.
func (b *AzurePrivateLinkSpecApplyConfiguration) WithAdditionalAllowedSubscriptions(values ...string) *AzurePrivateLinkSpecApplyConfiguration {
	for i := range values {
		b.AdditionalAllowedSubscriptions = append(b.AdditionalAllowedSubscriptions, values[i])
	}
	return b
}
