/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// AzureNodePoolOSDiskApplyConfiguration represents a declarative configuration of the AzureNodePoolOSDisk type for use
// with apply.
type AzureNodePoolOSDiskApplyConfiguration struct {
	SizeGiB                *int32                                         `json:"sizeGiB,omitempty"`
	DiskStorageAccountType *hypershiftv1beta1.AzureDiskStorageAccountType `json:"diskStorageAccountType,omitempty"`
	EncryptionSetID        *string                                        `json:"encryptionSetID,omitempty"`
	Persistence            *hypershiftv1beta1.AzureDiskPersistence        `json:"persistence,omitempty"`
}

// AzureNodePoolOSDiskApplyConfiguration constructs a declarative configuration of the AzureNodePoolOSDisk type for use with
// apply.
func AzureNodePoolOSDisk() *AzureNodePoolOSDiskApplyConfiguration {
	return &AzureNodePoolOSDiskApplyConfiguration{}
}

// WithSizeGiB sets the SizeGiB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeGiB field is set to the value of the last call.
func (b *AzureNodePoolOSDiskApplyConfiguration) WithSizeGiB(value int32) *AzureNodePoolOSDiskApplyConfiguration {
	b.SizeGiB = &value
	return b
}

// WithDiskStorageAccountType sets the DiskStorageAccountType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskStorageAccountType field is set to the value of the last call.
func (b *AzureNodePoolOSDiskApplyConfiguration) WithDiskStorageAccountType(value hypershiftv1beta1.AzureDiskStorageAccountType) *AzureNodePoolOSDiskApplyConfiguration {
	b.DiskStorageAccountType = &value
	return b
}

// WithEncryptionSetID sets the EncryptionSetID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EncryptionSetID field is set to the value of the last call.
func (b *AzureNodePoolOSDiskApplyConfiguration) WithEncryptionSetID(value string) *AzureNodePoolOSDiskApplyConfiguration {
	b.EncryptionSetID = &value
	return b
}

// WithPersistence sets the Persistence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Persistence field is set to the value of the last call.
func (b *AzureNodePoolOSDiskApplyConfiguration) WithPersistence(value hypershiftv1beta1.AzureDiskPersistence) *AzureNodePoolOSDiskApplyConfiguration {
	b.Persistence = &value
	return b
}
