/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// CapabilitiesApplyConfiguration represents an declarative configuration of the Capabilities type for use
// with apply.
type CapabilitiesApplyConfiguration struct {
	DisabledCapabilities []v1beta1.OptionalCapability `json:"disabledCapabilities,omitempty"`
}

// CapabilitiesApplyConfiguration constructs an declarative configuration of the Capabilities type for use with
// apply.
func Capabilities() *CapabilitiesApplyConfiguration {
	return &CapabilitiesApplyConfiguration{}
}

// WithDisabledCapabilities adds the given value to the DisabledCapabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DisabledCapabilities field.
func (b *CapabilitiesApplyConfiguration) WithDisabledCapabilities(values ...v1beta1.OptionalCapability) *CapabilitiesApplyConfiguration {
	for i := range values {
		b.DisabledCapabilities = append(b.DisabledCapabilities, values[i])
	}
	return b
}
