/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// CapacityReservationOptionsApplyConfiguration represents a declarative configuration of the CapacityReservationOptions type for use
// with apply.
type CapacityReservationOptionsApplyConfiguration struct {
	ID         *string                                          `json:"id,omitempty"`
	MarketType *hypershiftv1beta1.MarketType                    `json:"marketType,omitempty"`
	Preference *hypershiftv1beta1.CapacityReservationPreference `json:"preference,omitempty"`
}

// CapacityReservationOptionsApplyConfiguration constructs a declarative configuration of the CapacityReservationOptions type for use with
// apply.
func CapacityReservationOptions() *CapacityReservationOptionsApplyConfiguration {
	return &CapacityReservationOptionsApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *CapacityReservationOptionsApplyConfiguration) WithID(value string) *CapacityReservationOptionsApplyConfiguration {
	b.ID = &value
	return b
}

// WithMarketType sets the MarketType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MarketType field is set to the value of the last call.
func (b *CapacityReservationOptionsApplyConfiguration) WithMarketType(value hypershiftv1beta1.MarketType) *CapacityReservationOptionsApplyConfiguration {
	b.MarketType = &value
	return b
}

// WithPreference sets the Preference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Preference field is set to the value of the last call.
func (b *CapacityReservationOptionsApplyConfiguration) WithPreference(value hypershiftv1beta1.CapacityReservationPreference) *CapacityReservationOptionsApplyConfiguration {
	b.Preference = &value
	return b
}
