/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ClusterAutoscalingApplyConfiguration represents a declarative configuration of the ClusterAutoscaling type for use
// with apply.
type ClusterAutoscalingApplyConfiguration struct {
	MaxNodesTotal        *int32  `json:"maxNodesTotal,omitempty"`
	MaxPodGracePeriod    *int32  `json:"maxPodGracePeriod,omitempty"`
	MaxNodeProvisionTime *string `json:"maxNodeProvisionTime,omitempty"`
	PodPriorityThreshold *int32  `json:"podPriorityThreshold,omitempty"`
}

// ClusterAutoscalingApplyConfiguration constructs a declarative configuration of the ClusterAutoscaling type for use with
// apply.
func ClusterAutoscaling() *ClusterAutoscalingApplyConfiguration {
	return &ClusterAutoscalingApplyConfiguration{}
}

// WithMaxNodesTotal sets the MaxNodesTotal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNodesTotal field is set to the value of the last call.
func (b *ClusterAutoscalingApplyConfiguration) WithMaxNodesTotal(value int32) *ClusterAutoscalingApplyConfiguration {
	b.MaxNodesTotal = &value
	return b
}

// WithMaxPodGracePeriod sets the MaxPodGracePeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPodGracePeriod field is set to the value of the last call.
func (b *ClusterAutoscalingApplyConfiguration) WithMaxPodGracePeriod(value int32) *ClusterAutoscalingApplyConfiguration {
	b.MaxPodGracePeriod = &value
	return b
}

// WithMaxNodeProvisionTime sets the MaxNodeProvisionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNodeProvisionTime field is set to the value of the last call.
func (b *ClusterAutoscalingApplyConfiguration) WithMaxNodeProvisionTime(value string) *ClusterAutoscalingApplyConfiguration {
	b.MaxNodeProvisionTime = &value
	return b
}

// WithPodPriorityThreshold sets the PodPriorityThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodPriorityThreshold field is set to the value of the last call.
func (b *ClusterAutoscalingApplyConfiguration) WithPodPriorityThreshold(value int32) *ClusterAutoscalingApplyConfiguration {
	b.PodPriorityThreshold = &value
	return b
}
