/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// ComponentLogLevelSpecApplyConfiguration represents a declarative configuration of the ComponentLogLevelSpec type for use
// with apply.
type ComponentLogLevelSpecApplyConfiguration struct {
	LogLevel *hypershiftv1beta1.LogLevel `json:"logLevel,omitempty"`
}

// ComponentLogLevelSpecApplyConfiguration constructs a declarative configuration of the ComponentLogLevelSpec type for use with
// apply.
func ComponentLogLevelSpec() *ComponentLogLevelSpecApplyConfiguration {
	return &ComponentLogLevelSpecApplyConfiguration{}
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *ComponentLogLevelSpecApplyConfiguration) WithLogLevel(value hypershiftv1beta1.LogLevel) *ComponentLogLevelSpecApplyConfiguration {
	b.LogLevel = &value
	return b
}
