/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// EncryptionKeyReferenceApplyConfiguration represents a declarative configuration of the EncryptionKeyReference type for use
// with apply.
type EncryptionKeyReferenceApplyConfiguration struct {
	Provider    *hypershiftv1beta1.SecretEncryptionProvider `json:"provider,omitempty"`
	Fingerprint *string                                     `json:"fingerprint,omitempty"`
}

// EncryptionKeyReferenceApplyConfiguration constructs a declarative configuration of the EncryptionKeyReference type for use with
// apply.
func EncryptionKeyReference() *EncryptionKeyReferenceApplyConfiguration {
	return &EncryptionKeyReferenceApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *EncryptionKeyReferenceApplyConfiguration) WithProvider(value hypershiftv1beta1.SecretEncryptionProvider) *EncryptionKeyReferenceApplyConfiguration {
	b.Provider = &value
	return b
}

// WithFingerprint sets the Fingerprint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fingerprint field is set to the value of the last call.
func (b *EncryptionKeyReferenceApplyConfiguration) WithFingerprint(value string) *EncryptionKeyReferenceApplyConfiguration {
	b.Fingerprint = &value
	return b
}
