/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// GCPPlatformSpecApplyConfiguration represents a declarative configuration of the GCPPlatformSpec type for use
// with apply.
type GCPPlatformSpecApplyConfiguration struct {
	Project          *string                                      `json:"project,omitempty"`
	Region           *string                                      `json:"region,omitempty"`
	NetworkConfig    *GCPNetworkConfigApplyConfiguration          `json:"networkConfig,omitempty"`
	EndpointAccess   *hypershiftv1beta1.GCPEndpointAccessType     `json:"endpointAccess,omitempty"`
	ResourceLabels   []GCPResourceLabelApplyConfiguration         `json:"resourceLabels,omitempty"`
	WorkloadIdentity *GCPWorkloadIdentityConfigApplyConfiguration `json:"workloadIdentity,omitempty"`
}

// GCPPlatformSpecApplyConfiguration constructs a declarative configuration of the GCPPlatformSpec type for use with
// apply.
func GCPPlatformSpec() *GCPPlatformSpecApplyConfiguration {
	return &GCPPlatformSpecApplyConfiguration{}
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *GCPPlatformSpecApplyConfiguration) WithProject(value string) *GCPPlatformSpecApplyConfiguration {
	b.Project = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *GCPPlatformSpecApplyConfiguration) WithRegion(value string) *GCPPlatformSpecApplyConfiguration {
	b.Region = &value
	return b
}

// WithNetworkConfig sets the NetworkConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkConfig field is set to the value of the last call.
func (b *GCPPlatformSpecApplyConfiguration) WithNetworkConfig(value *GCPNetworkConfigApplyConfiguration) *GCPPlatformSpecApplyConfiguration {
	b.NetworkConfig = value
	return b
}

// WithEndpointAccess sets the EndpointAccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointAccess field is set to the value of the last call.
func (b *GCPPlatformSpecApplyConfiguration) WithEndpointAccess(value hypershiftv1beta1.GCPEndpointAccessType) *GCPPlatformSpecApplyConfiguration {
	b.EndpointAccess = &value
	return b
}

// WithResourceLabels adds the given value to the ResourceLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceLabels field.
func (b *GCPPlatformSpecApplyConfiguration) WithResourceLabels(values ...*GCPResourceLabelApplyConfiguration) *GCPPlatformSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceLabels")
		}
		b.ResourceLabels = append(b.ResourceLabels, *values[i])
	}
	return b
}

// WithWorkloadIdentity sets the WorkloadIdentity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadIdentity field is set to the value of the last call.
func (b *GCPPlatformSpecApplyConfiguration) WithWorkloadIdentity(value *GCPWorkloadIdentityConfigApplyConfiguration) *GCPPlatformSpecApplyConfiguration {
	b.WorkloadIdentity = value
	return b
}
