/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// HCPEtcdBackupStorageApplyConfiguration represents a declarative configuration of the HCPEtcdBackupStorage type for use
// with apply.
type HCPEtcdBackupStorageApplyConfiguration struct {
	StorageType *hypershiftv1beta1.HCPEtcdBackupStorageType `json:"storageType,omitempty"`
	S3          *HCPEtcdBackupS3ApplyConfiguration          `json:"s3,omitempty"`
	AzureBlob   *HCPEtcdBackupAzureBlobApplyConfiguration   `json:"azureBlob,omitempty"`
}

// HCPEtcdBackupStorageApplyConfiguration constructs a declarative configuration of the HCPEtcdBackupStorage type for use with
// apply.
func HCPEtcdBackupStorage() *HCPEtcdBackupStorageApplyConfiguration {
	return &HCPEtcdBackupStorageApplyConfiguration{}
}

// WithStorageType sets the StorageType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageType field is set to the value of the last call.
func (b *HCPEtcdBackupStorageApplyConfiguration) WithStorageType(value hypershiftv1beta1.HCPEtcdBackupStorageType) *HCPEtcdBackupStorageApplyConfiguration {
	b.StorageType = &value
	return b
}

// WithS3 sets the S3 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3 field is set to the value of the last call.
func (b *HCPEtcdBackupStorageApplyConfiguration) WithS3(value *HCPEtcdBackupS3ApplyConfiguration) *HCPEtcdBackupStorageApplyConfiguration {
	b.S3 = value
	return b
}

// WithAzureBlob sets the AzureBlob field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AzureBlob field is set to the value of the last call.
func (b *HCPEtcdBackupStorageApplyConfiguration) WithAzureBlob(value *HCPEtcdBackupAzureBlobApplyConfiguration) *HCPEtcdBackupStorageApplyConfiguration {
	b.AzureBlob = value
	return b
}
