/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "github.com/openshift/api/config/v1"
)

// IBMCloudPlatformSpecApplyConfiguration represents a declarative configuration of the IBMCloudPlatformSpec type for use
// with apply.
type IBMCloudPlatformSpecApplyConfiguration struct {
	ProviderType *v1.IBMCloudProviderType `json:"providerType,omitempty"`
}

// IBMCloudPlatformSpecApplyConfiguration constructs a declarative configuration of the IBMCloudPlatformSpec type for use with
// apply.
func IBMCloudPlatformSpec() *IBMCloudPlatformSpecApplyConfiguration {
	return &IBMCloudPlatformSpecApplyConfiguration{}
}

// WithProviderType sets the ProviderType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderType field is set to the value of the last call.
func (b *IBMCloudPlatformSpecApplyConfiguration) WithProviderType(value v1.IBMCloudProviderType) *IBMCloudPlatformSpecApplyConfiguration {
	b.ProviderType = &value
	return b
}
