/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	hypershiftv1beta1 "github.com/openshift/hypershift/client/applyconfiguration/hypershift/v1beta1"
)

// KarpenterConfigApplyConfiguration represents an declarative configuration of the KarpenterConfig type for use
// with apply.
type KarpenterConfigApplyConfiguration struct {
	Platform *v1beta1.PlatformType                 `json:"platform,omitempty"`
	AWS      *KarpenterAWSConfigApplyConfiguration `json:"aws,omitempty"`
}

// KarpenterConfigApplyConfiguration constructs an declarative configuration of the KarpenterConfig type for use with
// apply.
func KarpenterConfig() *KarpenterConfigApplyConfiguration {
	return &KarpenterConfigApplyConfiguration{}
}

// WithPlatform sets the Platform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Platform field is set to the value of the last call.
func (b *KarpenterConfigApplyConfiguration) WithPlatform(value v1beta1.PlatformType) *KarpenterConfigApplyConfiguration {
	b.Platform = &value
	return b
}

// WithAWS sets the AWS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AWS field is set to the value of the last call.
func (b *KarpenterConfigApplyConfiguration) WithAWS(value *KarpenterAWSConfigApplyConfiguration) *KarpenterConfigApplyConfiguration {
	b.AWS = value
	return b
}
