/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// MonitoringSpecApplyConfiguration represents a declarative configuration of the MonitoringSpec type for use
// with apply.
type MonitoringSpecApplyConfiguration struct {
	MetricsForwarding *MetricsForwardingSpecApplyConfiguration `json:"metricsForwarding,omitempty"`
	MetricsSet        *hypershiftv1beta1.MetricsSet            `json:"metricsSet,omitempty"`
}

// MonitoringSpecApplyConfiguration constructs a declarative configuration of the MonitoringSpec type for use with
// apply.
func MonitoringSpec() *MonitoringSpecApplyConfiguration {
	return &MonitoringSpecApplyConfiguration{}
}

// WithMetricsForwarding sets the MetricsForwarding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsForwarding field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithMetricsForwarding(value *MetricsForwardingSpecApplyConfiguration) *MonitoringSpecApplyConfiguration {
	b.MetricsForwarding = value
	return b
}

// WithMetricsSet sets the MetricsSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsSet field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithMetricsSet(value hypershiftv1beta1.MetricsSet) *MonitoringSpecApplyConfiguration {
	b.MetricsSet = &value
	return b
}
