/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// OpenStackPlatformSpecApplyConfiguration represents an declarative configuration of the OpenStackPlatformSpec type for use
// with apply.
type OpenStackPlatformSpecApplyConfiguration struct {
	CloudsYamlSecret *v1.LocalObjectReference `json:"cloudsYamlSecret,omitempty"`
	CACertSecret     *v1.LocalObjectReference `json:"caCertSecret,omitempty"`
}

// OpenStackPlatformSpecApplyConfiguration constructs an declarative configuration of the OpenStackPlatformSpec type for use with
// apply.
func OpenStackPlatformSpec() *OpenStackPlatformSpecApplyConfiguration {
	return &OpenStackPlatformSpecApplyConfiguration{}
}

// WithCloudsYamlSecret sets the CloudsYamlSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudsYamlSecret field is set to the value of the last call.
func (b *OpenStackPlatformSpecApplyConfiguration) WithCloudsYamlSecret(value v1.LocalObjectReference) *OpenStackPlatformSpecApplyConfiguration {
	b.CloudsYamlSecret = &value
	return b
}

// WithCACertSecret sets the CACertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CACertSecret field is set to the value of the last call.
func (b *OpenStackPlatformSpecApplyConfiguration) WithCACertSecret(value v1.LocalObjectReference) *OpenStackPlatformSpecApplyConfiguration {
	b.CACertSecret = &value
	return b
}
