/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// OperatorConfigurationApplyConfiguration represents a declarative configuration of the OperatorConfiguration type for use
// with apply.
type OperatorConfigurationApplyConfiguration struct {
	ClusterVersionOperator     *ClusterVersionOperatorSpecApplyConfiguration             `json:"clusterVersionOperator,omitempty"`
	ClusterNetworkOperator     *ClusterNetworkOperatorSpecApplyConfiguration             `json:"clusterNetworkOperator,omitempty"`
	IngressOperator            *IngressOperatorSpecApplyConfiguration                    `json:"ingressOperator,omitempty"`
	KubeAPIServer              *KubeAPIServerOperatorSpecApplyConfiguration              `json:"kubeAPIServer,omitempty"`
	Etcd                       *EtcdOperatorSpecApplyConfiguration                       `json:"etcd,omitempty"`
	KubeControllerManager      *KubeControllerManagerOperatorSpecApplyConfiguration      `json:"kubeControllerManager,omitempty"`
	KubeScheduler              *KubeSchedulerOperatorSpecApplyConfiguration              `json:"kubeScheduler,omitempty"`
	OpenShiftControllerManager *OpenShiftControllerManagerOperatorSpecApplyConfiguration `json:"openShiftControllerManager,omitempty"`
	OpenShiftAPIServer         *OpenShiftAPIServerOperatorSpecApplyConfiguration         `json:"openShiftAPIServer,omitempty"`
	OpenShiftOAuthAPIServer    *OpenShiftOAuthAPIServerOperatorSpecApplyConfiguration    `json:"openShiftOAuthAPIServer,omitempty"`
	OAuthServer                *OAuthServerOperatorSpecApplyConfiguration                `json:"oauthServer,omitempty"`
}

// OperatorConfigurationApplyConfiguration constructs a declarative configuration of the OperatorConfiguration type for use with
// apply.
func OperatorConfiguration() *OperatorConfigurationApplyConfiguration {
	return &OperatorConfigurationApplyConfiguration{}
}

// WithClusterVersionOperator sets the ClusterVersionOperator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterVersionOperator field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithClusterVersionOperator(value *ClusterVersionOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.ClusterVersionOperator = value
	return b
}

// WithClusterNetworkOperator sets the ClusterNetworkOperator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterNetworkOperator field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithClusterNetworkOperator(value *ClusterNetworkOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.ClusterNetworkOperator = value
	return b
}

// WithIngressOperator sets the IngressOperator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressOperator field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithIngressOperator(value *IngressOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.IngressOperator = value
	return b
}

// WithKubeAPIServer sets the KubeAPIServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeAPIServer field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithKubeAPIServer(value *KubeAPIServerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.KubeAPIServer = value
	return b
}

// WithEtcd sets the Etcd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Etcd field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithEtcd(value *EtcdOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.Etcd = value
	return b
}

// WithKubeControllerManager sets the KubeControllerManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeControllerManager field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithKubeControllerManager(value *KubeControllerManagerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.KubeControllerManager = value
	return b
}

// WithKubeScheduler sets the KubeScheduler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeScheduler field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithKubeScheduler(value *KubeSchedulerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.KubeScheduler = value
	return b
}

// WithOpenShiftControllerManager sets the OpenShiftControllerManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenShiftControllerManager field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithOpenShiftControllerManager(value *OpenShiftControllerManagerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.OpenShiftControllerManager = value
	return b
}

// WithOpenShiftAPIServer sets the OpenShiftAPIServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenShiftAPIServer field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithOpenShiftAPIServer(value *OpenShiftAPIServerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.OpenShiftAPIServer = value
	return b
}

// WithOpenShiftOAuthAPIServer sets the OpenShiftOAuthAPIServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenShiftOAuthAPIServer field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithOpenShiftOAuthAPIServer(value *OpenShiftOAuthAPIServerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.OpenShiftOAuthAPIServer = value
	return b
}

// WithOAuthServer sets the OAuthServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OAuthServer field is set to the value of the last call.
func (b *OperatorConfigurationApplyConfiguration) WithOAuthServer(value *OAuthServerOperatorSpecApplyConfiguration) *OperatorConfigurationApplyConfiguration {
	b.OAuthServer = value
	return b
}
