/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// OVNIPv6ConfigApplyConfiguration represents a declarative configuration of the OVNIPv6Config type for use
// with apply.
type OVNIPv6ConfigApplyConfiguration struct {
	InternalTransitSwitchSubnet *string `json:"internalTransitSwitchSubnet,omitempty"`
	InternalJoinSubnet          *string `json:"internalJoinSubnet,omitempty"`
}

// OVNIPv6ConfigApplyConfiguration constructs a declarative configuration of the OVNIPv6Config type for use with
// apply.
func OVNIPv6Config() *OVNIPv6ConfigApplyConfiguration {
	return &OVNIPv6ConfigApplyConfiguration{}
}

// WithInternalTransitSwitchSubnet sets the InternalTransitSwitchSubnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalTransitSwitchSubnet field is set to the value of the last call.
func (b *OVNIPv6ConfigApplyConfiguration) WithInternalTransitSwitchSubnet(value string) *OVNIPv6ConfigApplyConfiguration {
	b.InternalTransitSwitchSubnet = &value
	return b
}

// WithInternalJoinSubnet sets the InternalJoinSubnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalJoinSubnet field is set to the value of the last call.
func (b *OVNIPv6ConfigApplyConfiguration) WithInternalJoinSubnet(value string) *OVNIPv6ConfigApplyConfiguration {
	b.InternalJoinSubnet = &value
	return b
}
