/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// UnmanagedEtcdShardSpecApplyConfiguration represents a declarative configuration of the UnmanagedEtcdShardSpec type for use
// with apply.
type UnmanagedEtcdShardSpecApplyConfiguration struct {
	Name      *string                               `json:"name,omitempty"`
	Resources []EtcdShardResourceApplyConfiguration `json:"resources,omitempty"`
	Endpoint  *string                               `json:"endpoint,omitempty"`
}

// UnmanagedEtcdShardSpecApplyConfiguration constructs a declarative configuration of the UnmanagedEtcdShardSpec type for use with
// apply.
func UnmanagedEtcdShardSpec() *UnmanagedEtcdShardSpecApplyConfiguration {
	return &UnmanagedEtcdShardSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *UnmanagedEtcdShardSpecApplyConfiguration) WithName(value string) *UnmanagedEtcdShardSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *UnmanagedEtcdShardSpecApplyConfiguration) WithResources(values ...*EtcdShardResourceApplyConfiguration) *UnmanagedEtcdShardSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResources")
		}
		b.Resources = append(b.Resources, *values[i])
	}
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *UnmanagedEtcdShardSpecApplyConfiguration) WithEndpoint(value string) *UnmanagedEtcdShardSpecApplyConfiguration {
	b.Endpoint = &value
	return b
}
