/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SnapshotConfigApplyConfiguration represents a declarative configuration of the SnapshotConfig type for use
// with apply.
type SnapshotConfigApplyConfiguration struct {
	Enabled                 *bool   `json:"enabled,omitempty"`
	MinInterval             *string `json:"minInterval,omitempty"`
	PerPodRetentionCount    *int32  `json:"perPodRetentionCount,omitempty"`
	NamespaceRetentionCount *int32  `json:"namespaceRetentionCount,omitempty"`
	VolumeSnapshotClassName *string `json:"volumeSnapshotClassName,omitempty"`
}

// SnapshotConfigApplyConfiguration constructs a declarative configuration of the SnapshotConfig type for use with
// apply.
func SnapshotConfig() *SnapshotConfigApplyConfiguration {
	return &SnapshotConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SnapshotConfigApplyConfiguration) WithEnabled(value bool) *SnapshotConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithMinInterval sets the MinInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinInterval field is set to the value of the last call.
func (b *SnapshotConfigApplyConfiguration) WithMinInterval(value string) *SnapshotConfigApplyConfiguration {
	b.MinInterval = &value
	return b
}

// WithPerPodRetentionCount sets the PerPodRetentionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerPodRetentionCount field is set to the value of the last call.
func (b *SnapshotConfigApplyConfiguration) WithPerPodRetentionCount(value int32) *SnapshotConfigApplyConfiguration {
	b.PerPodRetentionCount = &value
	return b
}

// WithNamespaceRetentionCount sets the NamespaceRetentionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceRetentionCount field is set to the value of the last call.
func (b *SnapshotConfigApplyConfiguration) WithNamespaceRetentionCount(value int32) *SnapshotConfigApplyConfiguration {
	b.NamespaceRetentionCount = &value
	return b
}

// WithVolumeSnapshotClassName sets the VolumeSnapshotClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSnapshotClassName field is set to the value of the last call.
func (b *SnapshotConfigApplyConfiguration) WithVolumeSnapshotClassName(value string) *SnapshotConfigApplyConfiguration {
	b.VolumeSnapshotClassName = &value
	return b
}
