apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-node-tuning-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/finalizers
  - events
  verbs:
  - "*"
