apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-tuning-operator
  name: node-tuning-operator
spec:
  ports:
  - name: metrics
    port: 60000
    protocol: TCP
    targetPort: 60000
  selector:
    name: cluster-node-tuning-operator
  type: ClusterIP
