apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: awsendpointservices.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: AWSEndpointService
    listKind: AWSEndpointServiceList
    plural: awsendpointservices
    singular: awsendpointservice
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
