apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hosted-cluster-config-operator
  namespace: HCP_NAMESPACE
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - patch
  - update
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - patch
  - update
  - create
  - list
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - patch
  - update
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes/status
  verbs:
  - patch
  - update
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedcontrolplanes/finalizers
  verbs:
  - get
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinesets
  - machines
  verbs:
  - get
  - patch
  - update
  - list
  - watch
