apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hosted-cluster-config-operator
  namespace: HCP_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hosted-cluster-config-operator
subjects:
- kind: ServiceAccount
  name: hosted-cluster-config-operator
