apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: example-kubevirt
  namespace: clusters
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.12.0-x86_64
  pullSecret:
    name: pull-secret
  sshKey:
    name: ssh-key
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
      generateID: abc123
      storageDriver:
        type: Default
  infraID: example-kubevirt-infra
  etcd:
    managed:
      storage:
        type: PersistentVolume
        persistentVolume:
          size: 4Gi
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: Route
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: OIDC
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
  dns:
    baseDomain: example.com