apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: example-aws
  namespace: clusters
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.12.0-x86_64
  pullSecret:
    name: pull-secret
  sshKey:
    name: ssh-key
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
  platform:
    type: AWS
    aws:
      region: us-east-1
      rolesRef:
        controlPlaneOperatorARN: arn:aws:iam::123456789012:role/control-plane-operator-role
        imageRegistryARN: arn:aws:iam::123456789012:role/image-registry-operator-role
        ingressARN: arn:aws:iam::123456789012:role/ingress-operator-role
        kubeCloudControllerARN: arn:aws:iam::123456789012:role/kube-cloud-controller-role
        networkARN: arn:aws:iam::123456789012:role/network-operator-role
        nodePoolManagementARN: arn:aws:iam::123456789012:role/node-pool-management-role
        storageARN: arn:aws:iam::123456789012:role/storage-operator-role
      cloudProviderConfig:
        subnet:
          id: subnet-0123456789abcdef0
        vpc: vpc-0123456789abcdef0
  infraID: example-aws-infra
  etcd:
    managed:
      storage:
        type: PersistentVolume
        persistentVolume:
          size: 4Gi
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: OIDC
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
  dns:
    baseDomain: example.com