version:  v2.0.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
  - module: 'sigs.k8s.io/kube-api-linter'
    version: '48643eb2563dfbcb2c6314efdbdb8e25a65f7bc4' # Replace with the latest version