kind: Service
apiVersion: v1
metadata:
  name: certified-operators
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    olm.catalogSource: certified-operators
  type: ClusterIP
