apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/ImageStreamImportMode: "true"
  name: hostedclusters.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: HostedCluster
    listKind: HostedClusterList
    plural: hostedclusters
    shortNames:
    - hc
    - hcs
    singular: hostedcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Version
      jsonPath: .status.version.history[?(@.state=="Completed")].version
      name: Version
      type: string
    - description: KubeConfig Secret
      jsonPath: .status.kubeconfig.name
      name: KubeConfig
      type: string
    - description: Progress
      jsonPath: .status.version.history[?(@.state!="")].state
      name: Progress
      type: string
    - description: Available
      jsonPath: .status.conditions[?(@.type=="Available")].status
      name: Available
      type: string
    - description: Progressing
      jsonPath: .status.conditions[?(@.type=="Progressing")].status
      name: Progressing
      type: string
    - description: Message
      jsonPath: .status.conditions[?(@.type=="Available")].message
      name: Message
      type: string
    name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
