apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-defrag-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-defrag-controller
subjects:
- kind: ServiceAccount
  name: etcd-defrag-controller
