apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-defrag-controller
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
