apiVersion: v1
kind: Service
metadata:
  name: etcd-discovery
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: client
  publishNotReadyAddresses: true
  selector:
    app: etcd
  type: ClusterIP
