apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-self-register
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
