apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-client
spec:
  clusterIP: None
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: metrics
    port: 2381
    protocol: TCP
    targetPort: metrics
  selector:
    app: etcd
  type: ClusterIP
