apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olm-collect-profiles
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pprof-cert"]
    verbs: ["get", "update"]
