apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olm-collect-profiles
subjects:
  - kind: ServiceAccount
    name: olm-collect-profiles
roleRef:
  kind: Role
  name: olm-collect-profiles
  apiGroup: rbac.authorization.k8s.io
