
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-oauth-apiserver
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openshift-oauth-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openshift-oauth-apiserver
    spec:
      containers:
      - command:
        - /usr/bin/oauth-apiserver
        env:
        - name: HTTP_PROXY
          value: socks5://127.0.0.1:8090
        - name: HTTPS_PROXY
          value: socks5://127.0.0.1:8090
        image: oauth-apiserver
        imagePullPolicy: IfNotPresent
        name: openshift-oauth-apiserver
        resources:
          requests:
            cpu: 150m
            memory: 80Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/certs/serving
          name: serving-cert
      terminationGracePeriodSeconds: 120
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 416
          secretName: openshift-oauth-apiserver-cert