apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ho-release-gate-run
spec:
  timeouts:
    pipeline: "6h0m0s"
    tasks: "5h30m0s"
    finally: "30m0s"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/Nirshal/hypershift
      - name: revision
        value: ho-release-gate-pipeline
      - name: pathInRepo
        value: .tekton/pipelines/ho-release-gate.yaml
