---
collections:
  - name: ansible.posix
    version: "1.5.4"
  - name: community.general
    version: "7.4.0"
  - name: containers.podman
    version: "1.10.1"
  - name: amazon.aws
    version: ">=5.0.0"
