githubConfigUrl: "https://github.com/openshift/hypershift"
githubConfigSecret: "github-app-secret"

minRunners: 1
maxRunners: 70

template:
  spec:
    containers:
      - name: runner
        image: quay.io/rh_ee_brcox/arc-runner@sha256:897c2265433960b2011a1fac3a39d0ce82e8e6ead8bd317b56715896ef16c368
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: runner
