#!/bin/bash
set -euo pipefail
script_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
HYPERSHIFT_DIR=${HYPERSHIFT_DIR:-$script_dir/../..}

NAMESPACE="${NAMESPACE:-clusters}"
NAME="${NAME:-example}"
cp_namespace="${NAMESPACE}-${NAME}"

kubeconfigfile="${script_dir}/hosted.kubeconfig"

${script_dir}/start-portforward

oc get secret localhost-kubeconfig -o jsonpath='{ .data.kubeconfig }' -n ${cp_namespace} | base64 -d > "${kubeconfigfile}"

echo "Fetched local kubeconfig to ${kubeconfigfile}"
