#!/bin/bash
set -euo pipefail
script_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
HYPERSHIFT_DIR=${HYPERSHIFT_DIR:-$script_dir/../..}

NAMESPACE="${NAMESPACE:-clusters}"
NAME="${NAME:-example}"

export NAMESPACE
export NAME

echo "Starting control plane operators"

${script_dir}/start-cpo &> ${script_dir}/start-cpo.log &
${script_dir}/start-hcco &> ${script_dir}/start-hcco.log &
