#!/bin/bash
set -euo pipefail
script_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
pidfile="${script_dir}/hcco.pid"
if [[ -f ${pidfile} ]]; then 
	echo "Stopping hosted cluster config operator"
	kill -9 $(cat ${pidfile}) || true
	rm ${pidfile}
else
	echo "No pid file found for hosted cluster config operator"
	exit 1
fi
   

