#!/bin/bash
set -euo pipefail
script_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
pidfile="${script_dir}/portfw.pid"
if [[ -f ${pidfile} ]]; then 
	echo "Stopping port forward"
	kill -9 $(cat ${pidfile}) || true
	rm ${pidfile}
else
	echo "No pid file found for port forwarder"
	exit 1
fi
   

