apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hypershift?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push"
      && target_branch == "main"
      && ( "control-plane-operator/***".pathChanged() ||
           "support/***".pathChanged() ||
           ".tekton/control-plane-operator*".pathChanged() ||
           "/Containerfile.control-plane-operator".pathChanged() )
    pipelinesascode.tekton.dev/pipeline: ".tekton/pipelines/common-operator-build.yaml"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: control-plane-operator
    appstudio.openshift.io/component: control-plane-operator-main
    pipelines.appstudio.openshift.io/type: build
  name: control-plane-operator-main-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/control-plane-operator-main:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
  - name: dockerfile
    value: /Containerfile.control-plane
  - name: path-context
    value: .
  pipelineRef:
    name: hypershift-common-operator-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-control-plane-operator-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
