apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hypershift?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[release-5.1]"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/pipeline: ".tekton/pipelines/nightly-release-build.yaml"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: hypershift-operator
    appstudio.openshift.io/component: 'hypershift-operator-{{target_branch}}-nightly'
    pipelines.appstudio.openshift.io/type: build
  name: hypershift-operator-release-nightly-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: 'quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-operator/hypershift-operator-nightly-unverified'
  - name: destination-image-tag
    # The image tag should end up like 5.0.0-0.nightly-2026-08-12-123456 depending on the target branch and push event timestamp
    value: '{{ cel:pac.target_branch.replace("release-", "") + ".0-0.nightly-" + body.created_at.replace("T", "-").replace(":", "").replace("Z", "")}}'
  - name: destination-imagestream
    value: 'hypershift/hypershift-operator-{{ target_branch }}-nightly'
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
  - name: dockerfile
    value: Containerfile.operator
  - name: path-context
    value: .
  pipelineRef:
    name: hypershift-nightly-release-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-hypershift-operator-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: cluster-credentials
    secret:
      secretName: hypershift-ci-cluster-credentials
status: {}
