apiVersion: v1
kind: Service
metadata:
  name: azure-dns-proxy
  namespace: HCP_NAMESPACE
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: private-router
