// Code generated by MockGen. DO NOT EDIT.
// Source: control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
//
// Generated by this command:
//
//	mockgen -source=control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go -package=awsprivatelink -destination=control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller_mock.go
//

// Package awsprivatelink is a generated GoMock package.
package awsprivatelink
