apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gomaxprocs-webhook
subjects:
- kind: ServiceAccount
  name: gomaxprocs-webhook
  namespace: hypershift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gomaxprocs-webhook



