#!/bin/bash
# Generated by: Claude AI via Cursor

set -o nounset
set -x

# This script deletes an Azure HostedCluster and associated Azure resources.
# It reuses the same variables from the other scripts in this folder.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load variables - check if vars.sh is available
if [[ -f "${SCRIPT_DIR}/vars.sh" ]]; then
    source "${SCRIPT_DIR}/vars.sh"
else
    echo "Error: vars.sh not found. Please ensure you're running this from the managed-azure directory."
    exit 1
fi

# Variables from vars.sh and user-vars.sh that we'll use
AZURE_CREDS=${AZURE_CREDS:?"Error: AZURE_CREDS is not set. Please check your user-vars.sh file."}
HYPERSHIFT_BINARY_PATH=${HYPERSHIFT_BINARY_PATH:?"Error: HYPERSHIFT_BINARY_PATH is not set. Please check your user-vars.sh file."}
PREFIX=${PREFIX:?"Error: PREFIX is not set. Please check your user-vars.sh file."}
PERSISTENT_RG_NAME=${PERSISTENT_RG_NAME:?"Error: PERSISTENT_RG_NAME is not set. Please check the vars.sh file."}

# Local variables following the same pattern as create_basic_hosted_cluster.sh
MANAGED_RG_NAME="${PREFIX}-managed-rg"
CUSTOMER_VNET_RG_NAME="${PREFIX}-customer-vnet-rg"
CUSTOMER_NSG_RG_NAME="${PREFIX}-customer-nsg-rg"
CLUSTER_NAME="${PREFIX}-hc"

# Delete the hosted cluster using hypershift destroy command.
# If the HostedCluster object doesn't exist (e.g. creation failed before it was applied),
# hypershift destroy will fail. We log the error but continue so Azure resource groups are
# still cleaned up below.
${HYPERSHIFT_BINARY_PATH}/hypershift destroy cluster azure \
    --name "$CLUSTER_NAME" \
    --azure-creds "$AZURE_CREDS" \
    --resource-group-name "$MANAGED_RG_NAME" \
    --dns-zone-rg-name "$PERSISTENT_RG_NAME" || \
    echo "Warning: hypershift destroy failed (cluster may not exist in management cluster), continuing with Azure resource group cleanup"

# Clean up the customer resource groups that were created for this cluster

# Delete customer NSG resource group
if az group show --name "$CUSTOMER_NSG_RG_NAME" >/dev/null 2>&1; then
    az group delete --name "$CUSTOMER_NSG_RG_NAME" --yes --no-wait
else
    echo "Customer NSG resource group $CUSTOMER_NSG_RG_NAME does not exist or already deleted"
fi

# Delete customer VNET resource group  
if az group show --name "$CUSTOMER_VNET_RG_NAME" >/dev/null 2>&1; then
    az group delete --name "$CUSTOMER_VNET_RG_NAME" --yes --no-wait
else
    echo "Customer VNET resource group $CUSTOMER_VNET_RG_NAME does not exist or already deleted"
fi

# Delete managed resource group (this contains the cluster resources)
if az group show --name "$MANAGED_RG_NAME" >/dev/null 2>&1; then
    az group delete --name "$MANAGED_RG_NAME" --yes --no-wait
else
    echo "Managed resource group $MANAGED_RG_NAME does not exist or already deleted"
fi

echo "Hosted cluster deletion completed. Resource group deletions are running in the background."
echo "You can check the status with: az group list --query \"[?starts_with(name, '$PREFIX')]\""

set +x