apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: hypershift-cpo-hotfix-template
spec:
  project: crt-redhat-acm-tenant
  variables:
  - name: ticketReference
    description: A reference to the Jira ticket, e.g., ocpbugs-123456
  - name: versionName
    description: A K8s-compliant name for the version
    defaultValue: "{{hyphenize .ticketReference}}"

  resources:
  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Application
    metadata:
      name: hypershift-cpo-hotfix-{{.versionName}}
    spec:
      displayName: "hypershift-cpo-hotfix-{{.versionName}}"

  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Component
    metadata:
      annotations:
        build.appstudio.openshift.io/request: configure-pac
        build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
        git-provider: github
        git-provider-url: https://github.com
        mintmaker.appstudio.redhat.com/disabled: "true"
      name: hypershift-cpo-hotfix-{{.versionName}}
    spec:
      application: "hypershift-cpo-hotfix-{{.versionName}}"
      componentName: "hypershift-cpo-hotfix-{{.versionName}}"
      containerImage: "quay.io/redhat-user-workloads/crt-redhat-acm-tenant/control-plane-operator-hotfix-{{.versionName}}"
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile.control-plane
          revision: "hotfix-{{.versionName}}"
          url: https://github.com/openshift/hypershift

  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: ImageRepository
    metadata:
      name: hypershift-cpo-hotfix-{{.versionName}}
      labels:
        appstudio.redhat.com/application: hypershift-cpo-hotfix-{{.versionName}}
        appstudio.redhat.com/component: hypershift-cpo-hotfix-{{.versionName}}
      annotations:
        image-controller.appstudio.redhat.com/update-component-image: 'true'
    spec:
      image:
        name: crt-redhat-acm-tenant/control-plane-operator-hotfix-{{.versionName}}
        visibility: public
      notifications:
        - config:
            url: 'https://bombino.preprod.api.redhat.com/v1/sbom/quay/push'
          event: repo_push
          method: webhook
          title: SBOM-event-to-Bombino
