apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller-manager
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cloud-controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud-controller-manager
    spec:
      containers:
      - args:
        - --cloud-provider=aws
        - --use-service-account-credentials=false
        - --kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig
        - --cloud-config=/etc/cloud/aws.conf
        - --configure-cloud-routes=false
        - --leader-elect=true
        - --leader-elect-lease-duration=137s
        - --leader-elect-renew-deadline=107s
        - --leader-elect-retry-period=26s
        - --leader-elect-resource-namespace=openshift-cloud-controller-manager
        - --authentication-kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig
        - --authorization-kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig
        command:
        - /bin/aws-cloud-controller-manager
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /etc/kubernetes/secrets/cloud-provider/credentials
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
        image: aws-cloud-controller-manager
        imagePullPolicy: IfNotPresent
        name: cloud-controller-manager
        resources:
          requests:
            cpu: 75m
            memory: 60Mi
        volumeMounts:
        - mountPath: /etc/cloud
          name: cloud-config
        - mountPath: /etc/aws
          name: cloud-controller-creds
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
        - mountPath: /etc/kubernetes/secrets/cloud-provider
          name: cloud-creds
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: service-network-admin-kubeconfig
      - configMap:
          defaultMode: 420
          name: aws-cloud-config
        name: cloud-config
      - name: cloud-controller-creds
        secret:
          defaultMode: 420
          secretName: cloud-controller-creds
      - name: cloud-creds
        secret:
          defaultMode: 420
          secretName: cloud-controller-creds
