/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	auditlogpersistencev1alpha1 "github.com/openshift/hypershift/api/auditlogpersistence/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AuditLogPersistenceConfigLister helps list AuditLogPersistenceConfigs.
// All objects returned here must be treated as read-only.
type AuditLogPersistenceConfigLister interface {
	// List lists all AuditLogPersistenceConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*auditlogpersistencev1alpha1.AuditLogPersistenceConfig, err error)
	// Get retrieves the AuditLogPersistenceConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*auditlogpersistencev1alpha1.AuditLogPersistenceConfig, error)
	AuditLogPersistenceConfigListerExpansion
}

// auditLogPersistenceConfigLister implements the AuditLogPersistenceConfigLister interface.
type auditLogPersistenceConfigLister struct {
	listers.ResourceIndexer[*auditlogpersistencev1alpha1.AuditLogPersistenceConfig]
}

// NewAuditLogPersistenceConfigLister returns a new AuditLogPersistenceConfigLister.
func NewAuditLogPersistenceConfigLister(indexer cache.Indexer) AuditLogPersistenceConfigLister {
	return &auditLogPersistenceConfigLister{listers.New[*auditlogpersistencev1alpha1.AuditLogPersistenceConfig](indexer, auditlogpersistencev1alpha1.Resource("auditlogpersistenceconfig"))}
}
