{
 "title": "Hosted Cluster Control Plane",
 "tags": [
  "hosted-control-planes",
  "control-plane-metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Rate by Verb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\"}[$__rate_interval])) by (verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API Error Rate by Resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", code=~\"5..\"}[$__rate_interval])) by (resource)",
     "legendFormat": "5xx {{ resource }}"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", code=~\"4..\"}[$__rate_interval])) by (resource)",
     "legendFormat": "4xx {{ resource }}"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{job=\"apiserver\"}) by (request_kind)",
     "legendFormat": "{{ request_kind }}"
    }
   ]
  },
  {
   "title": "API Request Latency (excluding WATCH)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", verb!=\"WATCH\"}[$__rate_interval])) by (verb, le))",
     "legendFormat": "p99 {{ verb }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", verb!=\"WATCH\"}[$__rate_interval])) by (verb, le))",
     "legendFormat": "p50 {{ verb }}"
    }
   ]
  },
  {
   "title": "API Server Storage Objects by Resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_storage_objects{job=\"apiserver\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "etcd Database Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"etcd\"}",
     "legendFormat": "DB size ({{ pod }})"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{job=\"etcd\"}",
     "legendFormat": "DB in-use ({{ pod }})"
    }
   ]
  },
  {
   "title": "etcd Disk Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\"}[$__rate_interval])) by (pod, le))",
     "legendFormat": "p99 WAL fsync ({{ pod }})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\"}[$__rate_interval])) by (pod, le))",
     "legendFormat": "p99 backend commit ({{ pod }})"
    }
   ]
  },
  {
   "title": "etcd Peer Network Round-Trip Time (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=\"etcd\"}[$__rate_interval])) by (pod, le))",
     "legendFormat": "p99 peer RTT ({{ pod }})"
    }
   ]
  },
  {
   "title": "etcd Leader Changes (per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"etcd\"}[1h])",
     "legendFormat": "leader changes/h ({{ pod }})"
    }
   ]
  },
  {
   "title": "etcd Has Leader",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_has_leader{job=\"etcd\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Cluster Operators & CVO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cluster Operator Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cluster_operator_up{job=\"cluster-version-operator\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Cluster Operator Conditions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "cluster_operator_conditions{job=\"cluster-version-operator\"}"
    }
   ]
  },
  {
   "title": "Cluster Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cluster_version{job=\"cluster-version-operator\", type=\"current\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Scheduling Rate & Results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scheduler_scheduling_attempt_duration_seconds_count{job=\"kube-scheduler\"}[$__rate_interval]))",
     "legendFormat": "scheduling attempts/s"
    },
    {
     "expr": "sum(rate(scheduler_schedule_attempts_total{job=\"kube-scheduler\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Pending Pods by Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scheduler_pending_pods{job=\"kube-scheduler\"}) by (queue)",
     "legendFormat": "pending ({{ queue }})"
    }
   ]
  },
  { "title": "Controller Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Controller Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"kube-controller-manager\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Controller Work Queue Adds Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"kube-controller-manager\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "OLM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "ClusterServiceVersion Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "csv_succeeded{job=\"olm-operator\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}