{
 "title": "HyperShift SLOs / SLIs Alberto playground",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "prowjob_id", "query": { "query": "label_values(prowjob_id)" } }
  ]
 },
 "panels": [
  { "title": "NodePools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "# NodePool time to available\n\nSLO 99% of NodePools are available in under 900s / 15min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(hypershift_nodepools_initial_rollout_duration_seconds{}[$__range]) < 900) / count(max_over_time(hypershift_nodepools_initial_rollout_duration_seconds{}[$__range]))"
    }
   ]
  },
  {
   "title": "NodePool Available Duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(max_over_time(hypershift_nodepools_initial_rollout_duration_seconds{prowjob_id=~\"$prowjob_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": {
    "content": "# NodePool deletion duration\n\nSLO 99% of NodePools are deleted in under 300s / 5min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(hypershift_nodepools_deletion_duration_seconds{}[$__range]) < 300) / count(max_over_time(hypershift_nodepools_deletion_duration_seconds{}[$__range]))"
    }
   ]
  },
  {
   "title": "NodePool Deletion Duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(max_over_time(hypershift_nodepools_deletion_duration_seconds{prowjob_id=~\"$prowjob_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "options": {
    "content": "# NodePool nodes status\n\nSLO All NodePools have 100% of their nodes available"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(hypershift_nodepools_available_replicas{cluster_name!=\"\"}[$__range])) / sum(last_over_time(hypershift_nodepools_size{cluster_name!=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "NodePool Nodes Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(hypershift_nodepools_size{prowjob_id=~\"$prowjob_id\"}[$__range])"
    },
    {
     "expr": "last_over_time(hypershift_nodepools_available_replicas{prowjob_id=~\"$prowjob_id\"}[$__range])"
    }
   ]
  },
  {
   "title": "HyperShift > Cluster deletion > duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 26 },
   "options": {
    "content": "# Hosted Cluster deletion duration\n\nSLO 99% of the hosted clusters deletion under 720s / 12min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(hypershift_cluster_deletion_duration_seconds{}[$__range]) < 720) / count(max_over_time(hypershift_cluster_deletion_duration_seconds{}[$__range]))"
    }
   ]
  },
  {
   "title": "HostedCluster deletion duration",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (max_over_time(hypershift_cluster_deletion_duration_seconds{prowjob_id=~\"$prowjob_id\"}[$__range])))"
    }
   ]
  },
  {
   "title": "hypershift_cluster_deletion_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hypershift_cluster_deletion_duration_seconds"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "options": {
    "content": "# Hosted Cluster guest cluster resources deletion duration\n\nSLO 100% of the hosted clusters resources deletion under 300s / 5min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(hypershift_cluster_guest_cloud_resources_deletion_duration_seconds{}[$__range]) < 300) / count(max_over_time(hypershift_cluster_deletion_duration_seconds{}[$__range]))"
    }
   ]
  },
  {
   "title": "HostedCluster guest cluster resources deletion duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "\nsort_desc(sum by (name) (max_over_time(hypershift_cluster_guest_cloud_resources_deletion_duration_seconds{prowjob_id=~\"$prowjob_id\"}[$__range])))"
    }
   ]
  },
  {
   "title": "hypershift_cluster_guest_cloud_resources_deletion_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hypershift_cluster_guest_cloud_resources_deletion_duration_seconds"
    }
   ]
  },
  {
   "title": "HyperShift > Cluster available > duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "options": {
    "content": "# Hosted Cluster time to available\n\nSLO 99% of the hosted clusters are available in under 300s / 5min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(hypershift_cluster_available_duration_seconds{}[$__range]) < 300) / count(max_over_time(hypershift_cluster_available_duration_seconds{}[$__range]))"
    }
   ]
  },
  {
   "title": "HostedCluster Available Duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (max_over_time(hypershift_cluster_available_duration_seconds{prowjob_id=~\"$prowjob_id\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Internal SLO",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 51 },
   "options": {
    "content": "# Infrastructure ready duration\n\nInternal SLO 100% of the infrastructure ready under 30s"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hypershift_hosted_cluster_transition_seconds_bucket{le=\"30\", condition=\"InfrastructureReady\"}[$__range])) / sum(rate(hypershift_hosted_cluster_transition_seconds_count{condition=\"InfrastructureReady\"}[$__range]))"
    }
   ]
  },
  {
   "title": "InfrastructureReady duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hypershift_hosted_cluster_transition_seconds_bucket{condition=\"InfrastructureReady\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Internal SLO",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 58 },
   "options": {
    "content": "# Etcd available duration\n\nInternal SLO 100% of the etcd available under 120s / 2min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hypershift_hosted_cluster_transition_seconds_bucket{le=\"120\", condition=\"EtcdAvailable\"}[$__range])) / sum(rate(hypershift_hosted_cluster_transition_seconds_count{condition=\"EtcdAvailable\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Etcd available duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hypershift_hosted_cluster_transition_seconds_bucket{condition=\"EtcdAvailable\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Internal SLO",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 65 },
   "options": {
    "content": "# DNS reachable duration\n\nInternal SLO 100% of the DNS reachable under 180s / 3min"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hypershift_hosted_cluster_transition_seconds_bucket{le=\"180\", condition=\"ExternalDNSReachable\"}[$__range])) / sum(rate(hypershift_hosted_cluster_transition_seconds_count{condition=\"ExternalDNSReachable\"}[$__range]))"
    }
   ]
  },
  {
   "title": "DNS reachable duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hypershift_hosted_cluster_transition_seconds_bucket{condition=\"ExternalDNSReachable\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Hypershift > Cluster > memory footprint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "Internal SLO",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 73 },
   "options": {
    "content": "# Hosted Cluster memory consumption\n\nInternal SLO 90% of the hosted clusters control plane memory consumption < 8GB"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\ncount (sum by(namespace) (max_over_time(hypershift:controlplane:component_memory_rss{namespace=~\"$namespace\", prowjob_id=~\"$prowjob_id\"}[$__range])) < 8000000000) / count (sum by(namespace) (max_over_time(hypershift:controlplane:component_memory_rss{namespace=~\"$namespace\", prowjob_id=~\"$prowjob_id\"}[$__range])))\n\n\n"
    }
   ]
  },
  {
   "title": "Memory Request per HCP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (hypershift:controlplane:component_memory_request{namespace=~\"$namespace\", prowjob_id=~\"$prowjob_id\"})"
    }
   ]
  }
 ]
}