kind: Service
apiVersion: v1
metadata:
  name: redhat-operators
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    olm.catalogSource: redhat-operators
  type: ClusterIP
