apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kube-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-scheduler
    spec:
      containers:
      - args:
        - --config=/etc/kubernetes/config/config.json
        - --tls-cert-file=/etc/kubernetes/certs/tls.crt
        - --tls-private-key-file=/etc/kubernetes/certs/tls.key
        - --secure-port=10259
        - --authentication-kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig
        - --authorization-kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig
        - -v=2
        command:
        - hyperkube
        - kube-scheduler
        image: hyperkube
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /livez
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: kube-scheduler
        ports:
        - containerPort: 10259
          name: client
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 150Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/certs
          name: serving-cert
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
        - mountPath: /etc/kubernetes/config
          name: scheduler-config
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-scheduler
        name: scheduler-config
      - name: serving-cert
        secret:
          defaultMode: 416
          secretName: scheduler-server
      - name: kubeconfig
        secret:
          defaultMode: 416
          secretName: kube-scheduler-kubeconfig
