name: Codespell (Reusable)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  codespell:
    name: Codespell
    runs-on: arc-runner-set
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: make verify-codespell
