name: CPO Container Sync (Reusable)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  cpo-container-sync:
    name: CPO Container Sync
    runs-on: arc-runner-set
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: make cpo-container-sync
