name: CPO Container Sync

on:
  pull_request:
    branches: [main]

jobs:
  cpo-container-sync:
    name: CPO Container Sync
    runs-on: arc-runner-set
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - run: make cpo-container-sync
