name: Create Tag

on:
  push:
    branches:
      - main
    paths:
      - releases/tags.yaml

jobs:
  create-tag:
    uses: openshift/hypershift/.github/workflows/create-tag-reusable.yaml@main
    permissions:
      contents: write
    secrets: inherit
