name: gocacheprog Tests (Reusable)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: gocacheprog Unit Tests
    runs-on: arc-runner-set
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        env:
          HOME: /tmp
        with:
          go-version-file: contrib/ci/gocacheprog/go.mod
          cache: false
      - name: Run tests
        run: cd contrib/ci/gocacheprog && go test -race -count=1 ./...
