name: gocacheprog Tests (Reusable)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: gocacheprog Unit Tests
    runs-on: arc-runner-set
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        env:
          HOME: /tmp
        with:
          go-version-file: contrib/ci/gocacheprog/go.mod
          cache: false
      - name: Run tests
        run: cd contrib/ci/gocacheprog && go test -race -count=1 ./...
