name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test:
    name: Unit Tests
    runs-on: arc-runner-set
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - run: make test
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        env:
          HOME: /tmp
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: cover.out
