name: Source Freshness

on:
  pull_request:
    branches:
      - main
      - release-4.22

jobs:
  call-main-verify:
    name: Call main verify workflow
    uses: openshift/hypershift/.github/workflows/verify-reusable.yaml@main
    permissions:
      contents: read
