name: Verify (Reusable)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    runs-on: arc-runner-set
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          if [ -n "${{ github.base_ref }}" ]; then
            git fetch origin "${{ github.base_ref }}:${{ github.base_ref }}"
          fi
      - run: make verify-ci
